#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "fileutils"

ROOT = File.expand_path("..", __dir__)
TABLE_DIR = File.join(ROOT, "_planning", "canon_build", "tables")

WORK_CANDIDATES_PATH = File.join(TABLE_DIR, "canon_work_candidates.tsv")
OMISSION_QUEUE_PATH = File.join(TABLE_DIR, "canon_omission_queue.tsv")
SCORING_INPUTS_PATH = File.join(TABLE_DIR, "canon_scoring_inputs.tsv")
SCORES_PATH = File.join(TABLE_DIR, "canon_scores.tsv")
REPLACEMENT_CANDIDATES_PATH = File.join(TABLE_DIR, "canon_replacement_candidates.tsv")

HEADERS = %w[
  transaction_id add_work_id add_title add_creator cut_work_id cut_title cut_creator
  packet_ids evidence_refs score_delta coverage_effect source_status_effect duplicate_check
  chronology_check boundary_check gate_status rationale notes
].freeze

def read_tsv(path)
  CSV.read(path, headers: true, col_sep: "\t").map(&:to_h)
end

def write_tsv(path, headers, rows)
  FileUtils.mkdir_p(File.dirname(path))
  CSV.open(path, "w", col_sep: "\t", force_quotes: false) do |csv|
    csv << headers
    rows.each { |row| csv << headers.map { |header| row.fetch(header, "") } }
  end
end

works = read_tsv(WORK_CANDIDATES_PATH).to_h { |row| [row.fetch("work_id"), row] }
omission_rows = read_tsv(OMISSION_QUEUE_PATH).to_h { |row| [row.fetch("work_id"), row] }
scoring_inputs = read_tsv(SCORING_INPUTS_PATH).to_h { |row| [row.fetch("work_id"), row] }
scores = read_tsv(SCORES_PATH)

rows = scores
       .select { |score| scoring_inputs.fetch(score.fetch("work_id")).fetch("scoring_readiness") == "ready_for_score_computation" }
       .sort_by { |score| [-score.fetch("final_score").to_f, score.fetch("work_id")] }
       .map.with_index(1) do |score, index|
         work = works.fetch(score.fetch("work_id"))
         omission = omission_rows.fetch(score.fetch("work_id"))
         final_score = score.fetch("final_score")

         {
           "transaction_id" => "x045_prefilter_#{index.to_s.rjust(4, "0")}",
           "add_work_id" => work.fetch("work_id"),
           "add_title" => work.fetch("canonical_title"),
           "add_creator" => work.fetch("creator_display"),
           "cut_work_id" => "",
           "cut_title" => "",
           "cut_creator" => "",
           "packet_ids" => "X045",
           "evidence_refs" => omission.fetch("evidence_refs"),
           "score_delta" => "+#{final_score} before_cut_score",
           "coverage_effect" => "adds_score_ready_source_backed_candidate_with_capped_coverage_bonus",
           "source_status_effect" => "add_candidate_source_debt_closed_cut_not_selected",
           "duplicate_check" => "pending_cut_candidate_and_author_cluster_review",
           "chronology_check" => "add_candidate_date_known_public_path_chronology_not_checked",
           "boundary_check" => "add_candidate_boundary_and_completion_gates_clear",
           "gate_status" => "blocked",
           "rationale" => "Score-ready add candidate prefilter only; no public replacement can occur until a cut candidate, score delta, chronology, duplicate, and path-count validation are generated.",
           "notes" => "Generated by X045 from canon_scores.tsv; blank cut fields are intentional blocked-prefilter state."
         }
       end

write_tsv(REPLACEMENT_CANDIDATES_PATH, HEADERS, rows)

puts "wrote #{REPLACEMENT_CANDIDATES_PATH.sub(ROOT + "/", "")} (#{rows.size} rows)"
