#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "yaml"

ROOT = File.expand_path("..", __dir__)
BUILD_DIR = File.join(ROOT, "_planning", "canon_build")
TABLE_DIR = File.join(BUILD_DIR, "tables")
SOURCE_ITEMS_FILE = File.join(TABLE_DIR, "canon_source_items.tsv")
SOURCE_REGISTRY_FILE = File.join(TABLE_DIR, "canon_source_registry.tsv")
MANIFEST_FILE = File.join(BUILD_DIR, "manifests", "canon_build_manifest.yml")

SOURCE_ITEM_HEADERS = %w[
  source_id source_item_id raw_title raw_creator raw_date source_rank source_section source_url source_citation
  matched_work_id match_method match_confidence evidence_type evidence_weight supports match_status notes
].freeze

SOURCE_REGISTRY_HEADERS = %w[
  source_id source_title source_type source_scope source_date source_citation edition editors_or_authors
  publisher coverage_limits extraction_method packet_ids extraction_status notes
].freeze

def read_tsv(path)
  CSV.read(path, headers: true, col_sep: "\t").map(&:to_h)
end

def write_tsv(path, headers, rows, sort_key:)
  CSV.open(path, "w", col_sep: "\t", write_headers: true, headers: headers) do |csv|
    rows.sort_by { |row| row[sort_key].to_s }.each do |row|
      csv << headers.map { |header| row[header].to_s }
    end
  end
end

def item(source_id:, source_item_id:, raw_title:, raw_creator: "", raw_date: "", source_rank: "", source_section: "",
         source_url:, source_citation:, matched_work_id: "", match_method: "", match_confidence: "",
         evidence_type:, evidence_weight:, supports:, match_status:, notes:)
  {
    "source_id" => source_id,
    "source_item_id" => source_item_id,
    "raw_title" => raw_title,
    "raw_creator" => raw_creator,
    "raw_date" => raw_date,
    "source_rank" => source_rank,
    "source_section" => source_section,
    "source_url" => source_url,
    "source_citation" => source_citation,
    "matched_work_id" => matched_work_id,
    "match_method" => match_method,
    "match_confidence" => match_confidence,
    "evidence_type" => evidence_type,
    "evidence_weight" => evidence_weight,
    "supports" => supports,
    "match_status" => match_status,
    "notes" => notes
  }
end

KOREAN_FICTION_URL = "https://cup.columbia.edu/book/modern-korean-fiction/9780231135139/"
KOREAN_PROSE_URL = "https://cup.columbia.edu/book/premodern-korean-literary-prose/9780231165808/"
RIENNER_URL = "https://www.rienner.com/title/The_Rienner_Anthology_of_African_Literature"

rows = [
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_001_a_lucky_day", raw_title: "A Lucky Day", raw_creator: "Hyon Chingon", source_rank: "1", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 1/22; no item-level original publication date in consulted public metadata."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_002_potatoes", raw_title: "Potatoes", raw_creator: "Kim Tongin", source_rank: "2", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", matched_work_id: "work_candidate_eastasia_lit_potato", match_method: "title_creator_variant_lti_original_work", match_confidence: "0.95", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "matched_current_path", notes: "Local current candidate is Potato by Kim Dong-in; LTI lists English translated title Potatoes for Gamja; romanization/title-number variant only."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_003_crows", raw_title: "Crows", raw_creator: "Yi T'aejun", source_rank: "3", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 3/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_004_the_shaman_painting", raw_title: "The Shaman Painting", raw_creator: "Kim Tongni", source_rank: "4", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", matched_work_id: "work_candidate_eastasia_lit_shaman_sorceress", match_method: "official_lti_title_variant", match_confidence: "0.96", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "matched_current_path", notes: "Local current candidate is The Shaman Sorceress by Kim Tongni; LTI links The Shaman Painting to Munyeodo and also lists Munyeodo as The Shaman Sorceress."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_005_the_white_rabbit", raw_title: "The White Rabbit", raw_creator: "Kim Yujong", source_rank: "5", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 5/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_006_wings", raw_title: "Wings", raw_creator: "Yi Sang", source_rank: "6", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", matched_work_id: "work_candidate_global_lit_wings_yi_sang", match_method: "title_creator_exact_local_candidate", match_confidence: "1.00", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "matched_current_path", notes: "Exact title and creator in local canon_work_candidates.tsv."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_007_when_the_buckwheat_blooms", raw_title: "When the Buckwheat Blooms", raw_creator: "Yi Hyosok", source_rank: "7", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 7/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_008_my_innocent_uncle", raw_title: "My Innocent Uncle", raw_creator: "Ch'ae Manshik", source_rank: "8", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 8/22; local Chae Man-sik candidate is Peace Under Heaven, not this story."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_009_the_ritual_at_the_well", raw_title: "The Ritual at the Well", raw_creator: "Ch'oe Chonghui", source_rank: "9", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 9/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_010_coarse_sand", raw_title: "Coarse Sand", raw_creator: "Hwang Sunwon", source_rank: "10", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 10/22; local Hwang Sun-won candidates are Cranes and The Descendants of Cain, not this story."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_011_far_from_home", raw_title: "Far from Home", raw_creator: "Yi Hoch'ol", source_rank: "11", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 11/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_012_seoul_1964_winter", raw_title: "Seoul: 1964, Winter", raw_creator: "Kim Sungok", source_rank: "12", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 12/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_013_another_mans_room", raw_title: "Another Man's Room", raw_creator: "Ch'oe Inho", source_rank: "13", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 13/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_014_the_son", raw_title: "The Son", raw_creator: "Kim Pukhyang", source_rank: "14", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 14/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_015_knifeblade", raw_title: "Knifeblade", raw_creator: "Cho Sehui", source_rank: "15", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 15/22; local The Dwarf candidate is a story cycle, not the exact story item."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_016_ballad", raw_title: "Ballad", raw_creator: "Ch'oe Illam", source_rank: "16", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 16/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_017_footprints_in_the_snow", raw_title: "Footprints in the Snow", raw_creator: "Yi Ch'ongjun", source_rank: "17", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 17/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_018_the_old_hatter", raw_title: "The Old Hatter", raw_creator: "Yi Munyol", source_rank: "18", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 18/22; local Yi Mun-yol candidate is Our Twisted Hero, not this story."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_019_mothers_hitching_post", raw_title: "Mother's Hitching Post", raw_creator: "Pak Wanso", source_rank: "19", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 19/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_020_wayfarer", raw_title: "Wayfarer", raw_creator: "O Chonghui", source_rank: "20", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 20/22; Google Books visible contents show a romanized original-title/date-like line, but publisher TOC gives no item date."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_021_the_gray_snowman", raw_title: "The Gray Snowman", raw_creator: "Ch'oe Yun", source_rank: "21", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 21/22; no high-confidence exact local candidate found."),
  item(source_id: "e018_columbia_modern_korean_fiction_2005", source_item_id: "e018_cmkf_2005_022_lizard", raw_title: "Lizard", raw_creator: "Kim Yongha", source_rank: "22", source_section: "Contents", source_url: KOREAN_FICTION_URL, source_citation: "Columbia University Press official contents", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher TOC item 22/22; local Kim Young-ha candidate is I Have the Right to Destroy Myself, not this story."),

  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_015_epic_of_sundiata", raw_title: "The Epic of Sundiata", raw_creator: "D.T. Niane", source_rank: "15", source_section: "PART 1. THE ORAL TRADITION > West Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only; possible Sunjata/Sundiata oral-epic boundary; not matched in pilot."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_042_equianos_travels", raw_title: "Equiano's Travels", raw_creator: "Olaudah Equaino", source_rank: "42", source_section: "PART 2. EARLY AFRICAN AUTOBIOGRAPHIES: THE SLAVE TRADE", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Publisher/WorldCat spell creator as Equaino; likely Equiano but raw retained; possible current-path alias deferred."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_043_african_travels_abu_bakr_al_siddiq", raw_title: "The African Travels of Abu Bakr Al-Siddiq", raw_creator: "Abu Bakr Al-Siddiq", source_rank: "43", source_section: "PART 2. EARLY AFRICAN AUTOBIOGRAPHIES: THE SLAVE TRADE", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_044_narrative_travels_ali_gazirmabe", raw_title: "Narrative of the Travels of Ali Gazirmabe", raw_creator: "Ali Eisami Gazirmabe", source_rank: "44", source_section: "PART 2. EARLY AFRICAN AUTOBIOGRAPHIES: THE SLAVE TRADE", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "WorldCat title wording differs slightly; publisher raw retained."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_045_narrative_samuel_ajayi_crowther", raw_title: "The Narrative of Samuel Ajayi Crowther", raw_creator: "Samuel Ajayi Crowther", source_rank: "45", source_section: "PART 2. EARLY AFRICAN AUTOBIOGRAPHIES: THE SLAVE TRADE", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_046_slave_boy_to_priest", raw_title: "Slave Boy to Priest", raw_creator: "Petro Kilekwa", source_rank: "46", source_section: "PART 2. EARLY AFRICAN AUTOBIOGRAPHIES: THE SLAVE TRADE", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_047_river_afram", raw_title: "River Afram", raw_creator: "Andrew Amankwa Opoku", source_rank: "47", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > West Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_048_dark_child_ch_2_3", raw_title: "The Dark Child (Chapters 2-3)", raw_creator: "Camara Laye", source_rank: "48", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > West Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", matched_work_id: "work_candidate_global_lit_dark_child", match_method: "title_creator_current_path_selection", match_confidence: "0.98", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "represented_by_selection", notes: "Explicit chapter selection; does not prove complete-work inclusion."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_049_jewels_of_shrine", raw_title: "The Jewels of the Shrine: A Play in One Act", raw_creator: "James Ene Henshaw", source_rank: "49", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > West Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_050_palm_wine_drinkard", raw_title: "The Palm-Wine Drinkard", raw_creator: "Amos Tutuola", source_rank: "50", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > West Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", matched_work_id: "work_candidate_palm_wine_drinkard", match_method: "title_creator_current_path", match_confidence: "0.98", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "represented_by_selection", notes: "TOC does not expose chapter range; treat as anthology selection pending scope check."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_051_dawn_heart_africa", raw_title: "Dawn in the Heart of Africa", raw_creator: "Patrice Emery Lumumba", source_rank: "51", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > Central Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_052_chaka_ch_3_4", raw_title: "Chaka (Chapters 3-4)", raw_creator: "Thomas Mofolo", source_rank: "52", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > Southern Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", matched_work_id: "work_candidate_chaka_mofolo", match_method: "title_creator_current_path_selection", match_confidence: "0.98", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "represented_by_selection", notes: "Explicit chapter selection; does not prove complete-work inclusion."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_053_contraction_enclosure_land", raw_title: "The Contraction and Enclosure of the Land", raw_creator: "St. J. Page Yako", source_rank: "53", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > Southern Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_054_land_people_once_living", raw_title: "The Land of the People Once Living", raw_creator: "Sob. W. Nkhuhlu", source_rank: "54", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > Southern Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_055_mine_boy_ch_4", raw_title: "Mine Boy (Chapter 4)", raw_creator: "Peter Abrahams", source_rank: "55", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > Southern Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", matched_work_id: "work_candidate_africa_lit_mine_boy", match_method: "title_creator_current_path_selection", match_confidence: "0.98", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "represented_by_selection", notes: "Explicit chapter selection; does not prove complete-work inclusion."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_056_exile_in_nigeria", raw_title: "Exile in Nigeria", raw_creator: "Es'kia Mphahlele", source_rank: "56", source_section: "PART 3. THE COLONIAL PERIOD, 1885-1956 > Southern Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_057_doum_tree_wad_hamid", raw_title: "The Doum Tree of Wad Hamid", raw_creator: "Tayeb Salih", source_rank: "57", source_section: "PART 4. THE POSTCOLONIAL PERIOD, 1957 TO THE PRESENT > North Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Do not collapse to other Tayeb Salih current-path works."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_058_country_boy", raw_title: "The Country Boy", raw_creator: "Yusuf Sibai", source_rank: "58", source_section: "PART 4. THE POSTCOLONIAL PERIOD, 1957 TO THE PRESENT > North Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Partial denominator pilot: first 20 explicit-creator items only."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_059_my_father_writes_to_my_mother", raw_title: "My Father Writes to My Mother", raw_creator: "Assia Djebar", source_rank: "59", source_section: "PART 4. THE POSTCOLONIAL PERIOD, 1957 TO THE PRESENT > North Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "inclusion", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Do not collapse to Djebar collection/novel candidates without source-level relation review."),
  item(source_id: "e014_rienner_anthology_african_lit_2007", source_item_id: "e014_rienner_060_mother_comes_of_age_ch_2_3", raw_title: "Mother Comes of Age (Chapters 2-3)", raw_creator: "Driss Chraibi", source_rank: "60", source_section: "PART 4. THE POSTCOLONIAL PERIOD, 1957 TO THE PRESENT > North Africa", source_url: RIENNER_URL, source_citation: "Lynne Rienner official contents; WorldCat public TOC cross-check", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "anthology_public_toc", match_status: "unmatched", notes: "Explicit chapter selection; not matched to other Driss Chraibi current-path titles."),

  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_001_tales_bizarre", raw_title: "Tales of the Bizarre (Sui-jon)", raw_creator: "Anonymous", source_rank: "1.1", source_section: "Part I > 1. Pre-Koryo Prose and Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_002_passion_pagoda", raw_title: "Passion Surrounding the Pagoda (Simhwa yo t'ap)", raw_creator: "Anonymous", source_rank: "1.2", source_section: "Part I > 1. Pre-Koryo Prose and Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Creator inherited from adjacent Tales of the Bizarre heading; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_003_bamboo_tube", raw_title: "Beauties in a Bamboo Tube (Chuktong minyo)", raw_creator: "Anonymous", source_rank: "1.3", source_section: "Part I > 1. Pre-Koryo Prose and Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Creator inherited from adjacent Tales of the Bizarre heading; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_004_old_man_dog", raw_title: "An Old Man Becomes a Dog (Noong hwa ku)", raw_creator: "Anonymous", source_rank: "1.4", source_section: "Part I > 1. Pre-Koryo Prose and Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Creator inherited from adjacent Tales of the Bizarre heading; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_005_mister_cash", raw_title: "The Tale of Mister Cash (Kongbang-jon)", raw_creator: "Im Ch'un", source_rank: "2.1", source_section: "Part I > 2. Koryo Period Prose Works", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Sem Vermeersch."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_006_master_malt", raw_title: "The Tale of Master Malt (Kuk Sonsaeng-jon)", raw_creator: "Yi Kyubo", source_rank: "2.2", source_section: "Part I > 2. Koryo Period Prose Works", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_007_boats_bribes", raw_title: "Of Boats and Bribes (Churoe-sol)", raw_creator: "Yi Kyubo", source_rank: "2.3", source_section: "Part I > 2. Koryo Period Prose Works", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translators: Michael Pettid and Marshall R. Pihl."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_008_kim_kaein", raw_title: "Kim Kaein", raw_creator: "Ch'oe Cha", source_rank: "2.4", source_section: "Part I > 2. Koryo Period Prose Works", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_009_hermit_mount_lion", raw_title: "The Tale of the Hermit of Mount Lion (Yesan unja-jon)", raw_creator: "Ch'oe Hae", source_rank: "2.5", source_section: "Part I > 2. Koryo Period Prose Works", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_010_mr_pak", raw_title: "The Tale of Mr. Pak (Pak-ssi-jon)", raw_creator: "Yi Saek", source_rank: "2.6", source_section: "Part I > 2. Koryo Period Prose Works", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Do not merge with anonymous Tale of Lady Pak without variant review."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_011_floating_jade_green", raw_title: "An Account of Drunken Merriment at Floating Jade-Green Pavilion (Ch'wiyu Pubyokchong-gi)", raw_creator: "Kim Sisup", source_rank: "3.1", source_section: "Part II > 3. Early Choson Short Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Gregory N. Evon."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_012_lady_pak", raw_title: "The Tale of Lady Pak (Pak-ssi-jon)", raw_creator: "Anonymous", source_rank: "4.1", source_section: "Part II > 4. Choson Long Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translators: Jeongsoo Shin and Peter Lee."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_013_two_sisters", raw_title: "A Tale of Two Sisters, Changhwa and Hongnyon (Changhwa Hongnyon-jon)", raw_creator: "Anonymous", source_rank: "4.2", source_section: "Part II > 4. Choson Long Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translators: Jeongsoo Shin and Peter Lee."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_014_moon_gazing_pavilion", raw_title: "The Pledge at the Banquet of Moon-Gazing Pavilion (Wanolhoe maengyon, excerpt)", raw_creator: "Anonymous", source_rank: "4.3", source_section: "Part II > 4. Choson Long Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Source explicitly marks excerpt; translator: Ksenia Chizhova."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_015_choe_chok", raw_title: "The Tale of Ch'oe Ch'ok (Ch'oe Ch'ok-jon)", raw_creator: "Cho Wihan", source_rank: "4.4", source_section: "Part II > 4. Choson Long Fiction", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Sookja Cho."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_016_idle_talk", raw_title: "Idle Talk and Humorous Stories in a Peaceful Era (T'aep'yong hanhwa kolgye-jon)", raw_creator: "So Kojong", source_rank: "5.1", source_section: "Part II > 5. Choson Period Unofficial Histories", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Collection heading; nested public TOC stories extracted separately."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_017_guest_gets_wife", raw_title: "The Guest Gets a Wife", raw_creator: "So Kojong", source_rank: "5.1a", source_section: "Part II > 5. Choson Period Unofficial Histories > Idle Talk", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Idle Talk; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_018_sage_affairs", raw_title: "The Sage and His Affairs", raw_creator: "So Kojong", source_rank: "5.1b", source_section: "Part II > 5. Choson Period Unofficial Histories > Idle Talk", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Idle Talk; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_019_wailing_ghost", raw_title: "The Wailing Ghost", raw_creator: "So Kojong", source_rank: "5.1c", source_section: "Part II > 5. Choson Period Unofficial Histories > Idle Talk", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Idle Talk; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_020_general_kim_ghosts", raw_title: "General Kim Who Was Afraid of Ghosts", raw_creator: "So Kojong", source_rank: "5.1d", source_section: "Part II > 5. Choson Period Unofficial Histories > Idle Talk", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Idle Talk; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_021_ou_yadam", raw_title: "Unofficial Narratives by Ou (Ou yadam)", raw_creator: "Yu Mongin", source_rank: "5.2", source_section: "Part II > 5. Choson Period Unofficial Histories", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Collection heading; nested public TOC stories extracted separately."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_022_ghosts_songgyungwan", raw_title: "Ghosts of the Songgyun'gwan (Songgyun'gwan kwisin)", raw_creator: "Yu Mongin", source_rank: "5.2a", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_023_fox_pass", raw_title: "Fox Pass (You kogae)", raw_creator: "Yu Mongin", source_rank: "5.2b", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_024_pak_yop_affair", raw_title: "The Clever Trick of Pak Yop to Have an Affair (Kkoe rul naeo sat'onghan Pak Yop)", raw_creator: "Yu Mongin", source_rank: "5.2c", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_025_kangnamdok_mother", raw_title: "The Mother of Kangnamdok (Kangnamdok moja)", raw_creator: "Yu Mongin", source_rank: "5.2d", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Hyangsoon Yi."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_026_komungo_palace_woman", raw_title: "The Komun'go of Sim Sugyong and a Palace Woman (Sim Sugyong ui komun'go wa kungnyo)", raw_creator: "Yu Mongin", source_rank: "5.2e", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_027_chinbok", raw_title: "The Life of Chinbok, a Licentious Woman (Umbu Chinbok ui ilsaeng)", raw_creator: "Yu Mongin", source_rank: "5.2f", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Hyangsoon Yi."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_028_starving_thief", raw_title: "The Starving Thief (Kumjurin tojok)", raw_creator: "Yu Mongin", source_rank: "5.2g", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_029_yi_yesun_buddhism", raw_title: "Yi Yesun Who Devoted Herself to Buddhism (Pulgyo-e Yi Yesun)", raw_creator: "Yu Mongin", source_rank: "5.2h", source_section: "Part II > 5. Choson Period Unofficial Histories > Ou yadam", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Ou yadam; translator: Hyangsoon Yi."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_030_past_present_laughs", raw_title: "Collection of Past and Present Laughs (Kogum soch'ong)", raw_creator: "Anonymous", source_rank: "5.3", source_section: "Part II > 5. Choson Period Unofficial Histories", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Collection heading; nested public TOC stories extracted separately."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_031_narrow_hole", raw_title: "Falsely Cutting the Narrow Hole (Yangyol kong ch'ak)", raw_creator: "Anonymous", source_rank: "5.3a", source_section: "Part II > 5. Choson Period Unofficial Histories > Past and Present Laughs", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Collection of Past and Present Laughs; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_032_son_in_law_ridiculed", raw_title: "The Son-in-Law Who Ridiculed His Father-in-Law (So cho puung)", raw_creator: "Anonymous", source_rank: "5.3b", source_section: "Part II > 5. Choson Period Unofficial Histories > Past and Present Laughs", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Collection of Past and Present Laughs; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_033_three_women_mute", raw_title: "Three Women Examine a Mute (Samnyo kom a)", raw_creator: "Anonymous", source_rank: "5.3c", source_section: "Part II > 5. Choson Period Unofficial Histories > Past and Present Laughs", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Collection of Past and Present Laughs; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_034_virgin_study", raw_title: "Prerequisite Study for a Virgin (Chonyo sonsup)", raw_creator: "Anonymous", source_rank: "5.3d", source_section: "Part II > 5. Choson Period Unofficial Histories > Past and Present Laughs", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Collection of Past and Present Laughs; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_035_five_marvels", raw_title: "The Five Marvels That Shook the Heart (Omyo tongsim)", raw_creator: "Anonymous", source_rank: "5.3e", source_section: "Part II > 5. Choson Period Unofficial Histories > Past and Present Laughs", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Nested story under Collection of Past and Present Laughs; translator: Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_036_master_yedok", raw_title: "The Tale of Master Yedok (Yedok sonsaeng-jon)", raw_creator: "Pak Chiwon", source_rank: "6.1", source_section: "Part II > 6. Late Choson Period", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Charles La Shure. Not matched to Jehol Diary without source-level containment review."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_037_on_names", raw_title: "On Names (Myongnon)", raw_creator: "Pak Chiwon", source_rank: "6.2", source_section: "Part II > 6. Late Choson Period", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translators: Youngmin Kim and Youngyeon Kim."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_038_ears_eyes_mouth_heart", raw_title: "The Book of Ears, Eyes, Mouth, and Heart (Immokkusimso)", raw_creator: "Yi Tongmu", source_rank: "6.3", source_section: "Part II > 6. Late Choson Period", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Jamie Jungmin Yoo."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_039_record_hardships", raw_title: "The Record of My Hardships (Kohaengnok)", raw_creator: "Lady Yi of Hansan", source_rank: "6.4", source_section: "Part II > 6. Late Choson Period", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Translator: Si Nae Park."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_040_kyechuk_diary", raw_title: "Diary of the Kyech'uk Year (Kyech'uk ilgi, excerpt)", raw_creator: "Anonymous", source_rank: "7.1", source_section: "Part II > 7. Palace Literature", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "unmatched", notes: "Source explicitly marks excerpt; translators: Kil Cha and Michael Pettid."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_041_song_hungbo", raw_title: "Song of Hungbo (Hungpo-ga, excerpt)", raw_creator: "Korean p'ansori tradition", source_rank: "8.1", source_section: "Part III > 8. P'ansori, Narratives in Song", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", matched_work_id: "work_candidate_scale_lit_tale_heungbu", match_method: "pansori_cycle_alias_excerpt", match_confidence: "0.92", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "represented_by_selection", notes: "Source explicitly marks excerpt; section says introduced and translated by Chan E. Park."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_042_song_sim_chong", raw_title: "Song of Sim Chong (Sim Chong-ga, excerpt)", raw_creator: "Korean p'ansori tradition", source_rank: "8.2", source_section: "Part III > 8. P'ansori, Narratives in Song", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", matched_work_id: "work_candidate_scale_lit_tale_sim_cheong", match_method: "pansori_cycle_alias_excerpt", match_confidence: "0.92", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "represented_by_selection", notes: "Source explicitly marks excerpt; section says introduced and translated by Chan E. Park."),
  item(source_id: "e018_columbia_premodern_korean_prose_2018", source_item_id: "e018_pkprose2018_043_song_chunhyang", raw_title: "Song of Ch'unhyang (Ch'unhyang-ga, excerpt)", raw_creator: "Korean p'ansori tradition", source_rank: "8.3", source_section: "Part III > 8. P'ansori, Narratives in Song", source_url: KOREAN_PROSE_URL, source_citation: "Columbia University Press official public contents", matched_work_id: "work_candidate_chunhyangjeon", match_method: "pansori_cycle_alias_excerpt", match_confidence: "0.93", evidence_type: "representative_selection", evidence_weight: "0.60", supports: "field_anthology_public_toc", match_status: "represented_by_selection", notes: "Source explicitly marks excerpt; section says introduced and translated by Chan E. Park.")
]

source_item_rows = read_tsv(SOURCE_ITEMS_FILE)
source_items_by_id = source_item_rows.to_h { |row| [row["source_item_id"], row] }
rows.each { |row| source_items_by_id[row["source_item_id"]] = row }
write_tsv(SOURCE_ITEMS_FILE, SOURCE_ITEM_HEADERS, source_items_by_id.values, sort_key: "source_item_id")

registry_rows = read_tsv(SOURCE_REGISTRY_FILE)
registry_by_id = registry_rows.to_h { |row| [row["source_id"], row] }
{
  "e018_columbia_modern_korean_fiction_2005" => ["extracted", "Complete 22-item public story TOC ingested; evidence generation waits on match/relation review."],
  "e018_columbia_premodern_korean_prose_2018" => ["extracted", "Public CUP contents ingested as 43 source-item rows; chapter-versus-nested-item granularity still reviewable."],
  "e014_rienner_anthology_african_lit_2007" => ["in_progress", "Partial 20-row public TOC pilot ingested; full anthology extraction still pending."]
}.each do |source_id, (status, notes)|
  next unless registry_by_id[source_id]

  registry_by_id[source_id]["extraction_status"] = status
  registry_by_id[source_id]["notes"] = notes
end
write_tsv(SOURCE_REGISTRY_FILE, SOURCE_REGISTRY_HEADERS, registry_by_id.values, sort_key: "source_id")

manifest = YAML.load_file(MANIFEST_FILE)
manifest["status"] = "source_item_batch_x020_e014_e018_ingested"
manifest["artifacts"]["source_items"] = "e001_ingested_x001_x006_pilot_x013_materialized_x020_e014_e018_source_items"
manifest["source_item_extraction_batch_x020"] = {
  "source_items_added_or_updated" => rows.size,
  "sources_touched" => 3,
  "complete_public_toc_sources" => 2,
  "partial_public_toc_sources" => 1,
  "evidence_rows_added" => 0,
  "status" => "source_items_ingested_matching_required",
  "direct_replacements" => 0
}
manifest["current_counts"] ||= {}
manifest["current_counts"]["source_items"] = source_items_by_id.size
manifest["current_counts"]["evidence_rows"] ||= 0
File.write(MANIFEST_FILE, manifest.to_yaml)

puts "ingested or updated #{rows.size} X020 E014/E018 source-item rows"
