#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "fileutils"
require "set"
require "yaml"

ROOT = File.expand_path("..", __dir__)
TABLE_DIR = File.join(ROOT, "_planning", "canon_build", "tables")

SOURCE_REGISTRY_PATH = File.join(TABLE_DIR, "canon_source_registry.tsv")
SOURCE_ITEMS_PATH = File.join(TABLE_DIR, "canon_source_items.tsv")
EVIDENCE_PATH = File.join(TABLE_DIR, "canon_evidence.tsv")
SOURCE_WEIGHTS_PATH = File.join(TABLE_DIR, "canon_source_weights.yml")

SUPPORTED_MATCH_STATUSES = %w[
  matched_current_path
  matched_candidate
  represented_by_selection
  duplicate_or_variant
].freeze

def read_tsv(path)
  CSV.read(path, headers: true, col_sep: "\t").map(&:to_h)
end

def tsv_headers(path)
  CSV.open(path, col_sep: "\t", &:readline)
end

def write_tsv(path, headers, rows)
  FileUtils.mkdir_p(File.dirname(path))
  CSV.open(path, "w", col_sep: "\t", force_quotes: false) do |csv|
    csv << headers
    rows.each { |row| csv << headers.map { |header| row.fetch(header, "") } }
  end
end

def evidence_id_for(source_item_id)
  "x017_ev_#{source_item_id.gsub(/[^A-Za-z0-9]+/, "_").downcase}"
end

def base_strength(weight)
  return "strong" if weight >= 0.80
  return "moderate" if weight >= 0.45

  "weak"
end

def evidence_strength(source_item, source_class_config)
  weight = source_item.fetch("evidence_weight", "0").to_f
  strength = base_strength(weight)
  strength = "moderate" if source_item.fetch("evidence_type") == "representative_selection" && strength == "strong"
  strength = "weak" if source_class_config.fetch("counts_for_canon_score", false) == false
  strength
end

source_registry = read_tsv(SOURCE_REGISTRY_PATH)
source_items = read_tsv(SOURCE_ITEMS_PATH)
evidence_rows = read_tsv(EVIDENCE_PATH)
source_weights = YAML.load_file(SOURCE_WEIGHTS_PATH)

sources_by_id = source_registry.to_h { |row| [row.fetch("source_id"), row] }
source_type_mapping = source_weights.fetch("source_type_mapping")
source_classes = source_weights.fetch("source_classes")
existing_source_item_ids = evidence_rows.map { |row| row.fetch("source_item_id", "") }.reject(&:empty?).to_set
existing_evidence_ids = evidence_rows.map { |row| row.fetch("evidence_id") }.to_set

created = 0

source_items.each do |source_item|
  next unless SUPPORTED_MATCH_STATUSES.include?(source_item.fetch("match_status"))
  next if source_item.fetch("matched_work_id", "").to_s.empty?
  next if existing_source_item_ids.include?(source_item.fetch("source_item_id"))

  source = sources_by_id.fetch(source_item.fetch("source_id"))
  source_class_key = source_type_mapping.fetch(source.fetch("source_type"))
  source_class = source_classes.fetch(source_class_key)
  evidence_id = evidence_id_for(source_item.fetch("source_item_id"))
  raise "Evidence ID collision: #{evidence_id}" if existing_evidence_ids.include?(evidence_id)

  counts_for_score = source_class.fetch("counts_for_canon_score", false)
  evidence_rows << {
    "evidence_id" => evidence_id,
    "work_id" => source_item.fetch("matched_work_id"),
    "source_id" => source_item.fetch("source_id"),
    "source_item_id" => source_item.fetch("source_item_id"),
    "evidence_type" => source_item.fetch("evidence_type"),
    "evidence_strength" => evidence_strength(source_item, source_class),
    "page_or_section" => source_item.fetch("source_section", ""),
    "quote_or_note" => "",
    "packet_id" => "X017",
    "supports_tier" => "",
    "supports_boundary_policy_id" => "",
    "reviewer_status" => "needs_followup",
    "notes" => "Generated by X017 from matched source item after X013 review. Source class #{source_class_key} has counts_for_canon_score=#{counts_for_score}; source debt is not closed until scoring and scope gates pass."
  }
  existing_source_item_ids << source_item.fetch("source_item_id")
  existing_evidence_ids << evidence_id
  created += 1
end

write_tsv(EVIDENCE_PATH, tsv_headers(EVIDENCE_PATH), evidence_rows)

puts "created #{created} evidence rows"
