#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "yaml"

ROOT = File.expand_path("..", __dir__)
BUILD_DIR = File.join(ROOT, "_planning", "canon_build")
TABLE_DIR = File.join(BUILD_DIR, "tables")
SOURCE_ITEMS_FILE = File.join(TABLE_DIR, "canon_source_items.tsv")
EVIDENCE_FILE = File.join(TABLE_DIR, "canon_evidence.tsv")
MANIFEST_FILE = File.join(BUILD_DIR, "manifests", "canon_build_manifest.yml")

SOURCE_ITEM_HEADERS = %w[
  source_id source_item_id raw_title raw_creator raw_date source_rank source_section source_url source_citation
  matched_work_id match_method match_confidence evidence_type evidence_weight supports match_status notes
].freeze

EVIDENCE_HEADERS = %w[
  evidence_id work_id source_id source_item_id evidence_type evidence_strength page_or_section quote_or_note
  packet_id supports_tier supports_boundary_policy_id reviewer_status notes
].freeze

def read_tsv(path)
  CSV.read(path, headers: true, col_sep: "\t").map(&:to_h)
end

def write_tsv(path, headers, rows)
  CSV.open(path, "w", col_sep: "\t", write_headers: true, headers: headers) do |csv|
    rows.sort_by { |row| row[headers[1]].to_s }.each do |row|
      csv << headers.map { |header| row[header].to_s }
    end
  end
end

def item(source_id:, source_item_id:, raw_title:, raw_creator: "", raw_date: "", source_rank: "", source_section: "",
         source_url:, source_citation:, matched_work_id: "", match_method: "", match_confidence: "",
         evidence_type:, evidence_weight:, supports:, match_status:, notes:)
  {
    "source_id" => source_id,
    "source_item_id" => source_item_id,
    "raw_title" => raw_title,
    "raw_creator" => raw_creator,
    "raw_date" => raw_date,
    "source_rank" => source_rank,
    "source_section" => source_section,
    "source_url" => source_url,
    "source_citation" => source_citation,
    "matched_work_id" => matched_work_id,
    "match_method" => match_method,
    "match_confidence" => match_confidence,
    "evidence_type" => evidence_type,
    "evidence_weight" => evidence_weight,
    "supports" => supports,
    "match_status" => match_status,
    "notes" => notes
  }
end

def evidence_for(row, packet_id, strength)
  evidence_id = "x001_x006_ev_#{row["source_item_id"].gsub(/[^a-zA-Z0-9]+/, "_").gsub(/\A_+|_+\z/, "")}"
  {
    "evidence_id" => evidence_id,
    "work_id" => row["matched_work_id"],
    "source_id" => row["source_id"],
    "source_item_id" => row["source_item_id"],
    "evidence_type" => row["evidence_type"],
    "evidence_strength" => strength,
    "page_or_section" => row["source_section"],
    "quote_or_note" => "",
    "packet_id" => packet_id,
    "supports_tier" => "",
    "supports_boundary_policy_id" => "",
    "reviewer_status" => "needs_followup",
    "notes" => "Pilot extraction row; source-item match/evidence weight requires X013-X016 normalization before source debt is closed."
  }
end

rows = [
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0012_tlg001",
    raw_title: "Iliad",
    raw_creator: "Homer",
    source_section: "CTS work urn:cts:greekLit:tlg0012.tlg001; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0012.tlg001",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_canon_iliad",
    match_method: "cts_urn_title_creator",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Metadata layer only; no source ranking or composition date."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0012_tlg002",
    raw_title: "Odyssey",
    raw_creator: "Homer",
    source_section: "CTS work urn:cts:greekLit:tlg0012.tlg002; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0012.tlg002",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_canon_odyssey",
    match_method: "cts_urn_title_creator",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Metadata layer only."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0011_tlg002",
    raw_title: "Antigone",
    raw_creator: "Sophocles",
    source_section: "CTS work urn:cts:greekLit:tlg0011.tlg002; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0011.tlg002",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_canon_antigone_sophocles",
    match_method: "cts_urn_title_creator",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Metadata layer only."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0011_tlg004",
    raw_title: "Oedipus Tyrannus",
    raw_creator: "Sophocles",
    source_section: "CTS work urn:cts:greekLit:tlg0011.tlg004; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0011.tlg004",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_canon_oedipus_tyrannus",
    match_method: "cts_urn_title_creator_alias",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Alias risk: Oedipus Rex and Oedipus the King."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0006_tlg003",
    raw_title: "Medea",
    raw_creator: "Euripides",
    source_section: "CTS work urn:cts:greekLit:tlg0006.tlg003; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0006.tlg003",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_candidate_medea_euripides",
    match_method: "cts_urn_title_creator",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Current path row is manual_only; metadata evidence does not close source debt alone."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0006_tlg017",
    raw_title: "Bacchae",
    raw_creator: "Euripides",
    source_section: "CTS work urn:cts:greekLit:tlg0006.tlg017; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0006.tlg017",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_candidate_euripides_bacchae_performance",
    match_method: "cts_urn_title_creator_alias",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Local title includes article: The Bacchae."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0019_tlg007",
    raw_title: "Lysistrata",
    raw_creator: "Aristophanes",
    source_section: "CTS work urn:cts:greekLit:tlg0019.tlg007; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0019.tlg007",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_candidate_lysistrata",
    match_method: "cts_urn_title_creator",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Current path row is manual_only; metadata evidence does not close source debt alone."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0016_tlg001",
    raw_title: "Histories",
    raw_creator: "Herodotus",
    source_section: "CTS work urn:cts:greekLit:tlg0016.tlg001; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0016.tlg001",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_canon_histories_herodotus",
    match_method: "cts_urn_title_creator",
    match_confidence: "0.99",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Generic title; creator-aware matching required."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0003_tlg001",
    raw_title: "History of the Peloponnesian War",
    raw_creator: "Thucydides",
    source_section: "CTS work urn:cts:greekLit:tlg0003.tlg001; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0003.tlg001",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_canon_peloponnesian_war_thucydides",
    match_method: "cts_urn_title_creator",
    match_confidence: "0.99",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "classical_metadata_presence",
    match_status: "matched_current_path",
    notes: "Metadata layer only."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0059_tlg011",
    raw_title: "Symposium",
    raw_creator: "Plato",
    source_section: "CTS work urn:cts:greekLit:tlg0059.tlg011; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0059.tlg011",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_candidate_mandatory_plato_symposium",
    match_method: "cts_urn_title_creator",
    match_confidence: "1.00",
    evidence_type: "boundary_context",
    evidence_weight: "0.25",
    supports: "classical_metadata_boundary_presence",
    match_status: "matched_current_path",
    notes: "Philosophical dialogue boundary; metadata presence only."
  ),
  item(
    source_id: "e008_perseus_catalog_greek_latin_works",
    source_item_id: "perseus_urn_cts_greeklit_tlg0086_tlg034",
    raw_title: "Poetics",
    raw_creator: "Aristotle",
    source_section: "CTS work urn:cts:greekLit:tlg0086.tlg034; work_lang=grc",
    source_url: "https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0086.tlg034",
    source_citation: "Perseus Catalog CTS work metadata",
    matched_work_id: "work_canon_poetics_aristotle",
    match_method: "cts_urn_title_creator",
    match_confidence: "1.00",
    evidence_type: "boundary_context",
    evidence_weight: "0.25",
    supports: "classical_metadata_boundary_presence",
    match_status: "matched_current_path",
    notes: "Poetics/literary theory boundary; metadata presence only."
  ),
  item(
    source_id: "e008_phi_classical_latin_texts",
    source_item_id: "phi_0690_003",
    raw_title: "Aeneis",
    raw_creator: "Publius Vergilius Maro",
    source_section: "Canon of Latin Authors; author=0690 work=003 abbr=A",
    source_url: "https://latin.packhum.org/loc/690/3/0",
    source_citation: "PHI Canon of Classical Latin Authors and Works",
    matched_work_id: "work_canon_aeneid",
    match_method: "phi_author_work_number_title_creator_alias",
    match_confidence: "0.99",
    evidence_type: "inclusion",
    evidence_weight: "0.45",
    supports: "latin_corpus_presence",
    match_status: "matched_current_path",
    notes: "Use canon metadata only; do not scrape text."
  ),
  item(
    source_id: "e008_phi_classical_latin_texts",
    source_item_id: "phi_0550_001",
    raw_title: "De Rerum Natura",
    raw_creator: "Titus Lucretius Carus",
    source_section: "Canon of Latin Authors; author=0550 work=001 abbr=DRN",
    source_url: "https://latin.packhum.org/loc/550/1/0",
    source_citation: "PHI Canon of Classical Latin Authors and Works",
    matched_work_id: "work_candidate_bloom_gap_031_0070_on_the_nature_of_things",
    match_method: "phi_author_work_number_title_creator_alias",
    match_confidence: "0.99",
    evidence_type: "inclusion",
    evidence_weight: "0.45",
    supports: "latin_corpus_presence",
    match_status: "matched_current_path",
    notes: "Local English title is On the Nature of Things."
  ),
  item(
    source_id: "e008_phi_classical_latin_texts",
    source_item_id: "phi_0959_006",
    raw_title: "Metamorphoses",
    raw_creator: "Publius Ovidius Naso",
    source_section: "Canon of Latin Authors; author=0959 work=006 abbr=Met",
    source_url: "https://latin.packhum.org/loc/959/6/0",
    source_citation: "PHI Canon of Classical Latin Authors and Works",
    matched_work_id: "work_candidate_metamorphoses_ovid",
    match_method: "phi_author_work_number_title_creator",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.45",
    supports: "latin_corpus_presence",
    match_status: "matched_current_path",
    notes: "Creator-aware matching required because Apuleius also has Metamorphoses."
  ),
  item(
    source_id: "e008_phi_classical_latin_texts",
    source_item_id: "phi_0972_001",
    raw_title: "Satyrica",
    raw_creator: "Petronius",
    source_section: "Canon of Latin Authors; author=0972 work=001 abbr=Sat",
    source_url: "https://latin.packhum.org/loc/972/1/0",
    source_citation: "PHI Canon of Classical Latin Authors and Works",
    matched_work_id: "work_canon_satyricon_petronius",
    match_method: "phi_author_work_number_title_creator_alias",
    match_confidence: "0.97",
    evidence_type: "inclusion",
    evidence_weight: "0.45",
    supports: "latin_corpus_presence",
    match_status: "matched_current_path",
    notes: "Local title Satyricon; source title Satyrica."
  ),
  item(
    source_id: "e008_phi_classical_latin_texts",
    source_item_id: "phi_1212_002",
    raw_title: "Metamorphoses",
    raw_creator: "Apuleius Madaurensis",
    source_section: "Canon of Latin Authors; author=1212 work=002 abbr=Met",
    source_url: "https://latin.packhum.org/loc/1212/2/0",
    source_citation: "PHI Canon of Classical Latin Authors and Works",
    matched_work_id: "work_candidate_golden_ass_apuleius",
    match_method: "phi_author_work_number_title_creator_alias",
    match_confidence: "0.97",
    evidence_type: "inclusion",
    evidence_weight: "0.45",
    supports: "latin_corpus_presence",
    match_status: "matched_current_path",
    notes: "Local title The Golden Ass; alias Metamorphoses."
  ),
  item(
    source_id: "library_of_america_catalog",
    source_item_id: "loa_catalog_068_douglass_narrative",
    raw_title: "Narrative of the Life of Frederick Douglass, an American Slave",
    raw_creator: "Frederick Douglass",
    raw_date: "1845",
    source_rank: "68",
    source_section: "LOA No. 68; contained work",
    source_url: "https://www.loa.org/books/37-autobiographies/",
    source_citation: "Library of America, Frederick Douglass: Autobiographies, LOA No. 68",
    matched_work_id: "work_candidate_bloom_reviewed_douglass_narrative",
    match_method: "title_creator_contained_work_exact",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.70",
    supports: "loa_catalog_edition_presence",
    match_status: "matched_current_path",
    notes: "Source rank is LOA volume number, not ranking."
  ),
  item(
    source_id: "library_of_america_catalog",
    source_item_id: "loa_catalog_074_hurston_their_eyes",
    raw_title: "Their Eyes Were Watching God",
    raw_creator: "Zora Neale Hurston",
    raw_date: "1937",
    source_rank: "74",
    source_section: "LOA No. 74; table of contents",
    source_url: "https://www.loa.org/books/52-novels-amp-stories/",
    source_citation: "Library of America, Zora Neale Hurston: Novels & Stories, LOA No. 74",
    matched_work_id: "work_candidate_their_eyes_were_watching_god",
    match_method: "title_creator_contained_work_exact",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.70",
    supports: "loa_catalog_edition_presence",
    match_status: "matched_current_path",
    notes: "Contained-work edition evidence."
  ),
  item(
    source_id: "library_of_america_catalog",
    source_item_id: "loa_catalog_098_baldwin_notes_native_son",
    raw_title: "Notes of a Native Son",
    raw_creator: "James Baldwin",
    raw_date: "1955",
    source_rank: "98",
    source_section: "LOA No. 98; table of contents",
    source_url: "https://www.loa.org/books/121-collected-essays/",
    source_citation: "Library of America, James Baldwin: Collected Essays, LOA No. 98",
    matched_work_id: "work_candidate_mandatory_baldwin_notes_native_son",
    match_method: "title_creator_contained_work_exact",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.70",
    supports: "loa_catalog_edition_presence",
    match_status: "matched_current_path",
    notes: "Contained-work edition evidence."
  ),
  item(
    source_id: "library_of_america_catalog",
    source_item_id: "loa_catalog_098_baldwin_fire_next_time",
    raw_title: "The Fire Next Time",
    raw_creator: "James Baldwin",
    raw_date: "1963",
    source_rank: "98",
    source_section: "LOA No. 98; table of contents",
    source_url: "https://www.loa.org/books/121-collected-essays/",
    source_citation: "Library of America, James Baldwin: Collected Essays, LOA No. 98",
    matched_work_id: "work_candidate_mandatory_baldwin_fire_next_time",
    match_method: "title_creator_contained_work_exact",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.70",
    supports: "loa_catalog_edition_presence",
    match_status: "matched_current_path",
    notes: "Contained-work edition evidence."
  ),
  item(
    source_id: "library_of_america_catalog",
    source_item_id: "loa_catalog_247_brown_clotel",
    raw_title: "Clotel; or, the President's Daughter",
    raw_creator: "William Wells Brown",
    raw_date: "1853",
    source_rank: "247",
    source_section: "LOA No. 247; table of contents",
    source_url: "https://www.loa.org/books/399-clotel-amp-other-writings/",
    source_citation: "Library of America, William Wells Brown: Clotel & Other Writings, LOA No. 247",
    matched_work_id: "work_candidate_mandatory_clotel",
    match_method: "title_alias_creator_exact",
    match_confidence: "0.96",
    evidence_type: "inclusion",
    evidence_weight: "0.70",
    supports: "loa_catalog_edition_presence",
    match_status: "matched_current_path",
    notes: "Title variant requires alias to Clotel."
  ),
  item(
    source_id: "e012_loa_slave_narratives",
    source_item_id: "e012_loa_sn_gronniosaw",
    raw_title: "Narrative of the Most Remarkable Particulars in the Life of James Albert Ukawsaw Gronniosaw, An African Prince, As related by Himself",
    raw_creator: "James Albert Ukawsaw Gronniosaw",
    raw_date: "1772",
    source_rank: "1",
    source_section: "Table of Contents; LOA No. 114",
    source_url: "https://www.loa.org/books/139-slave-narratives/",
    source_citation: "Library of America, Slave Narratives, LOA No. 114",
    match_method: "no_safe_match",
    evidence_type: "inclusion",
    evidence_weight: "0.85",
    supports: "authoritative_collection_inclusion",
    match_status: "unmatched",
    notes: "No current work candidate found in checked tables."
  ),
  item(
    source_id: "e012_loa_slave_narratives",
    source_item_id: "e012_loa_sn_equiano",
    raw_title: "The Interesting Narrative of the Life of Olaudah Equiano, or Gustavus Vassa, the African. Written by Himself",
    raw_creator: "Olaudah Equiano",
    raw_date: "1789",
    source_rank: "2",
    source_section: "Table of Contents; LOA No. 114",
    source_url: "https://www.loa.org/books/139-slave-narratives/",
    source_citation: "Library of America, Slave Narratives, LOA No. 114",
    matched_work_id: "work_candidate_mandatory_equiano_interesting_narrative",
    match_method: "title_alias_creator_exact",
    match_confidence: "0.93",
    evidence_type: "inclusion",
    evidence_weight: "0.85",
    supports: "authoritative_collection_inclusion",
    match_status: "matched_current_path",
    notes: "Local canonical title is abbreviated."
  ),
  item(
    source_id: "e012_loa_slave_narratives",
    source_item_id: "e012_loa_sn_nat_turner",
    raw_title: "The Confessions of Nat Turner, the Leader of the Late Insurrection in Southhampton, VA.",
    raw_creator: "Nat Turner",
    raw_date: "1831",
    source_rank: "3",
    source_section: "Table of Contents; LOA No. 114",
    source_url: "https://www.loa.org/books/139-slave-narratives/",
    source_citation: "Library of America, Slave Narratives, LOA No. 114",
    match_method: "no_safe_match",
    evidence_type: "inclusion",
    evidence_weight: "0.85",
    supports: "authoritative_collection_inclusion",
    match_status: "unmatched",
    notes: "Source spelling says Southhampton; likely alias risk."
  ),
  item(
    source_id: "e012_loa_slave_narratives",
    source_item_id: "e012_loa_sn_douglass_narrative",
    raw_title: "Narrative of the Life of Frederick Douglass, An American Slave",
    raw_creator: "Frederick Douglass",
    raw_date: "1845",
    source_rank: "4",
    source_section: "Table of Contents; LOA No. 114",
    source_url: "https://www.loa.org/books/139-slave-narratives/",
    source_citation: "Library of America, Slave Narratives, LOA No. 114",
    matched_work_id: "work_candidate_bloom_reviewed_douglass_narrative",
    match_method: "title_creator_exact",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.85",
    supports: "authoritative_collection_inclusion",
    match_status: "matched_current_path",
    notes: "Duplicate support also appears in LOA No. 68."
  ),
  item(
    source_id: "e012_loa_slave_narratives",
    source_item_id: "e012_loa_sn_brown_narrative",
    raw_title: "Narrative of William W. Brown, A Fugitive Slave. Written by Himself",
    raw_creator: "William Wells Brown",
    raw_date: "1847",
    source_rank: "5",
    source_section: "Table of Contents; LOA No. 114",
    source_url: "https://www.loa.org/books/139-slave-narratives/",
    source_citation: "Library of America, Slave Narratives, LOA No. 114",
    match_method: "no_safe_match",
    evidence_type: "inclusion",
    evidence_weight: "0.85",
    supports: "authoritative_collection_inclusion",
    match_status: "unmatched",
    notes: "Do not collapse into Clotel candidate."
  ),
  item(
    source_id: "e012_loa_slave_narratives",
    source_item_id: "e012_loa_sn_jacobs_incidents",
    raw_title: "Incidents in the Life of a Slave Girl. Written by Herself",
    raw_creator: "Harriet Ann Jacobs",
    raw_date: "1861",
    source_rank: "9",
    source_section: "Table of Contents; LOA No. 114",
    source_url: "https://www.loa.org/books/139-slave-narratives/",
    source_citation: "Library of America, Slave Narratives, LOA No. 114",
    matched_work_id: "work_candidate_mandatory_jacobs_incidents",
    match_method: "title_alias_creator_exact",
    match_confidence: "0.97",
    evidence_type: "inclusion",
    evidence_weight: "0.85",
    supports: "authoritative_collection_inclusion",
    match_status: "matched_current_path",
    notes: "Creator alias Harriet Ann Jacobs vs Harriet Jacobs."
  ),
  item(
    source_id: "e012_loa_african_american_poetry_2020",
    source_item_id: "e012_aap_wheatley_on_imagination",
    raw_title: "On Imagination",
    raw_creator: "Phillis Wheatley",
    source_section: "ONE: BURY ME IN A FREE LAND 1770-1899",
    source_url: "https://loa-shared.s3-us-west-2.amazonaws.com/static/pdf/African_American_Poetry_TOC.pdf",
    source_citation: "Library of America, African American Poetry: 250 Years of Struggle & Song, TOC PDF",
    matched_work_id: "work_candidate_mandatory_wheatley_poems",
    match_method: "poem_to_collection_candidate",
    match_confidence: "0.86",
    evidence_type: "representative_selection",
    evidence_weight: "0.50",
    supports: "poem_level_anthology_inclusion",
    match_status: "represented_by_selection",
    notes: "Poem row supports selection basis, not whole collection by itself."
  ),
  item(
    source_id: "e012_loa_african_american_poetry_2020",
    source_item_id: "e012_aap_harper_bury_me_free_land",
    raw_title: "Bury Me in a Free Land",
    raw_creator: "Frances Ellen Watkins Harper",
    source_section: "ONE: BURY ME IN A FREE LAND 1770-1899",
    source_url: "https://loa-shared.s3-us-west-2.amazonaws.com/static/pdf/African_American_Poetry_TOC.pdf",
    source_citation: "Library of America, African American Poetry: 250 Years of Struggle & Song, TOC PDF",
    match_method: "no_safe_work_level_match",
    evidence_type: "representative_selection",
    evidence_weight: "0.50",
    supports: "poem_level_anthology_inclusion",
    match_status: "unmatched",
    notes: "Do not match to Iola Leroy; no Harper poetry candidate found."
  ),
  item(
    source_id: "e012_loa_african_american_poetry_2020",
    source_item_id: "e012_aap_dunbar_we_wear_mask",
    raw_title: "We Wear the Mask",
    raw_creator: "Paul Laurence Dunbar",
    source_section: "TWO: LIFT EVERY VOICE 1900-1918",
    source_url: "https://loa-shared.s3-us-west-2.amazonaws.com/static/pdf/African_American_Poetry_TOC.pdf",
    source_citation: "Library of America, African American Poetry: 250 Years of Struggle & Song, TOC PDF",
    matched_work_id: "work_candidate_wave002_dunbar_lyrics_lowly_life",
    match_method: "poem_alias_to_selection_candidate",
    match_confidence: "0.95",
    evidence_type: "representative_selection",
    evidence_weight: "0.50",
    supports: "poem_level_anthology_inclusion",
    match_status: "represented_by_selection",
    notes: "Local alias exists for poem title."
  ),
  item(
    source_id: "e012_loa_african_american_poetry_2020",
    source_item_id: "e012_aap_hughes_negro_speaks_rivers",
    raw_title: "The Negro Speaks of Rivers",
    raw_creator: "Langston Hughes",
    source_section: "THREE: THE DARK TOWER 1919-1936",
    source_url: "https://loa-shared.s3-us-west-2.amazonaws.com/static/pdf/African_American_Poetry_TOC.pdf",
    source_citation: "Library of America, African American Poetry: 250 Years of Struggle & Song, TOC PDF",
    matched_work_id: "work_candidate_bloom_reviewed_hughes_poems",
    match_method: "poem_alias_to_selection_candidate",
    match_confidence: "0.95",
    evidence_type: "representative_selection",
    evidence_weight: "0.50",
    supports: "poem_level_anthology_inclusion",
    match_status: "represented_by_selection",
    notes: "Local alias exists for poem title."
  ),
  item(
    source_id: "icelandic_saga_database",
    source_item_id: "icelandic_saga_database_brennu_njals_saga",
    raw_title: "The Story of Burnt Njal / Brennu-Njals saga",
    raw_creator: "Icelandic saga tradition; tr. George W. Dasent",
    raw_date: "original 13th-14th c.; English tr. 1861",
    source_section: "A-Z index; English page",
    source_url: "https://sagadb.org/brennu-njals_saga.en",
    source_citation: "Icelandic Saga Database, Brennu-Njals saga / The Story of Burnt Njal",
    matched_work_id: "work_candidate_njals_saga",
    match_method: "original_title_alias_translation_title",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "identity_alias_text_access",
    match_status: "matched_current_path",
    notes: "Family-saga source; not canon-selection evidence."
  ),
  item(
    source_id: "icelandic_saga_database",
    source_item_id: "icelandic_saga_database_egils_saga",
    raw_title: "Egil's Saga / Egils saga Skalla-Grimssonar",
    raw_creator: "Icelandic saga tradition; tr. W. C. Green",
    raw_date: "original 13th c.; English tr. 1893",
    source_section: "A-Z index; English page",
    source_url: "https://sagadb.org/egils_saga.en",
    source_citation: "Icelandic Saga Database, Egils saga",
    matched_work_id: "work_candidate_completion_lit_egils_saga",
    match_method: "original_title_alias_translation_title",
    match_confidence: "0.98",
    evidence_type: "inclusion",
    evidence_weight: "0.35",
    supports: "identity_alias_text_access",
    match_status: "matched_current_path",
    notes: "Title variants require alias rows."
  ),
  item(
    source_id: "philobiblon_iberian_romance",
    source_item_id: "philobiblon_biteca_texid_1754_tirant",
    raw_title: "Tirant lo Blanc",
    raw_creator: "Joanot Martorell, Cavaller",
    raw_date: "escrit 1460-01-02 a quo - 1490 ad quem",
    source_section: "BITECA Work texid 1754",
    source_url: "https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1754BITECA.Work.xml&style=Work.xsl",
    source_citation: "PhiloBiblon BITECA texid 1754",
    matched_work_id: "work_candidate_euro_under_lit_tirant_lo_blanc",
    match_method: "authority_title_creator",
    match_confidence: "0.99",
    evidence_type: "inclusion",
    evidence_weight: "0.40",
    supports: "identity_witness_language",
    match_status: "matched_current_path",
    notes: "Three witnesses; Catalan work record."
  ),
  item(
    source_id: "philobiblon_iberian_romance",
    source_item_id: "philobiblon_biteca_texid_1112_curial",
    raw_title: "Curial e Guelfa",
    raw_creator: "Desconegut",
    raw_date: "escrit 1440 [?] - 1480 [?]",
    source_section: "BITECA Work texid 1112",
    source_url: "https://philobiblon.upf.edu/xtf/servlet/org.cdlib.xtf.dynaXML.DynaXML?source=unified/Display/1112BITECA.Work.xml&style=Work.xsl",
    source_citation: "PhiloBiblon BITECA texid 1112",
    match_method: "unmatched_source_candidate",
    evidence_type: "inclusion",
    evidence_weight: "0.25",
    supports: "candidate_discovery",
    match_status: "unmatched",
    notes: "No current work match found; possible Catalan chivalric-novel gap."
  ),
  item(
    source_id: "arlima_medieval_literature",
    source_item_id: "arlima_chretien_perceval",
    raw_title: "Perceval ou le Conte du Graal",
    raw_creator: "Chretien de Troyes",
    raw_date: "entre 1182 et 1190",
    source_section: "ARLIMA work page",
    source_url: "https://www.arlima.net/ad/chretien_de_troyes/perceval_ou_le_conte_du_graal.html",
    source_citation: "ARLIMA, Perceval ou le Conte du Graal",
    matched_work_id: "work_candidate_mandatory_perceval_grail",
    match_method: "authority_title_creator_date",
    match_confidence: "0.99",
    evidence_type: "inclusion",
    evidence_weight: "0.40",
    supports: "identity_alias_manuscripts",
    match_status: "matched_current_path",
    notes: "ARLIMA lists manuscripts, continuations, translations."
  ),
  item(
    source_id: "arlima_medieval_literature",
    source_item_id: "arlima_queste_saint_graal",
    raw_title: "La queste del Saint Graal",
    raw_creator: "Old French Vulgate prose tradition",
    raw_date: "1225-1230",
    source_section: "ARLIMA work page",
    source_url: "https://www.arlima.net/qt/queste_del_saint_graal.html",
    source_citation: "ARLIMA, La queste del Saint Graal",
    matched_work_id: "work_candidate_scale_lit_quest_holy_grail",
    match_method: "authority_title_cycle_match",
    match_confidence: "0.96",
    evidence_type: "inclusion",
    evidence_weight: "0.40",
    supports: "identity_cycle_manuscripts",
    match_status: "matched_current_path",
    notes: "Part of Lancelot-Grail/Vulgate cycle."
  ),
  item(
    source_id: "dante_digital_anchor_layer",
    source_item_id: "dante_pdp_commedia",
    raw_title: "Commedia / Divine Comedy",
    raw_creator: "Dante Alighieri",
    raw_date: "c. 1308-1321",
    source_section: "PDP Commedia",
    source_url: "https://dante.princeton.edu/dante/pdp/commedia.html",
    source_citation: "Princeton Dante Project, Dante's Divine Comedy",
    matched_work_id: "work_canon_divine_comedy",
    match_method: "exact_specialist_project_match",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.50",
    supports: "text_commentary_identity",
    match_status: "matched_current_path",
    notes: "PDP exposes Inferno/Purgatorio/Paradiso structure."
  ),
  item(
    source_id: "dante_digital_anchor_layer",
    source_item_id: "dante_pdp_vita_nuova",
    raw_title: "Vita nuova",
    raw_creator: "Dante Alighieri",
    raw_date: "c. 1290s",
    source_section: "PDP minor works",
    source_url: "https://dante.princeton.edu/dante/pdp/vnuova.html",
    source_citation: "Princeton Dante Project, Minor Works: Vita Nuova",
    matched_work_id: "work_candidate_completion_lit_vita_nuova",
    match_method: "exact_specialist_project_match",
    match_confidence: "0.99",
    evidence_type: "inclusion",
    evidence_weight: "0.45",
    supports: "text_commentary_identity",
    match_status: "matched_current_path",
    notes: "Dante minor-work match."
  ),
  item(
    source_id: "norton_english_lit_11e_full_2024",
    source_item_id: "norton_nael11e_vola_beowulf",
    raw_title: "Beowulf",
    source_rank: "1",
    source_section: "Volume A > The Middle Ages > Literature of the Early Middle Ages",
    source_url: "https://cdn.wwnorton.com/marketing/college/misc_marketing_assets/LITERATURE_NAEL11e_volA_5pp_i-v_lr_NewMaterial_EM_SL.pdf",
    source_citation: "W. W. Norton official NAEL 11e Volume A TOC PDF",
    matched_work_id: "work_canon_beowulf",
    match_method: "title_match_current_path",
    match_confidence: "0.95",
    evidence_type: "inclusion",
    evidence_weight: "0.80",
    supports: "anthology_public_toc",
    match_status: "matched_current_path",
    notes: "TOC only; classify complete/excerpt before source debt is closed."
  ),
  item(
    source_id: "longman_brit_lit_middle_ages_1a_4e",
    source_item_id: "longman_1a_4e_beowulf",
    raw_title: "BEOWULF",
    source_rank: "1",
    source_section: "THE MIDDLE AGES > Before the Norman Conquest",
    source_url: "https://www.pearson.com/en-us/subject-catalog/p/longman-anthology-of-british-literature-the-the-middle-ages-volume-1a/P200000002130",
    source_citation: "Pearson official product TOC",
    matched_work_id: "work_canon_beowulf",
    match_method: "title_match_current_path",
    match_confidence: "0.95",
    evidence_type: "inclusion",
    evidence_weight: "0.80",
    supports: "anthology_public_toc",
    match_status: "matched_current_path",
    notes: "Creator not explicit in TOC line."
  ),
  item(
    source_id: "broadview_brit_lit_medieval_r3_2023",
    source_item_id: "broadview_medieval_r3_exeter_wanderer",
    raw_title: "The Wanderer",
    source_rank: "1",
    source_section: "EXETER BOOK ELEGIES",
    source_url: "https://broadviewpress.com/product/the-broadview-anthology-of-british-literature-volume-1-the-medieval-period-revised-third-edition/",
    source_citation: "Broadview official product TOC",
    match_method: "unmatched_source_candidate",
    evidence_type: "representative_selection",
    evidence_weight: "0.60",
    supports: "anthology_public_toc",
    match_status: "unmatched",
    notes: "Section heading supplies manuscript cluster, not creator; needs contained-work policy."
  ),
  item(
    source_id: "broadview_medieval_drama_2012",
    source_item_id: "broadview_medieval_drama_hrosvitha_abraham",
    raw_title: "Abraham",
    raw_creator: "Hrotsvitha of Gandersheim",
    source_rank: "1",
    source_section: "HROTSVITHA OF GANDERSHEIM",
    source_url: "https://broadviewpress.com/product/the-broadview-anthology-of-medieval-drama/",
    source_citation: "Broadview official product TOC",
    match_method: "unmatched_source_candidate",
    evidence_type: "inclusion",
    evidence_weight: "0.60",
    supports: "anthology_public_toc",
    match_status: "unmatched",
    notes: "Drama anthology; title is a play."
  ),
  item(
    source_id: "columbia_lithum_current_2026",
    source_item_id: "columbia_lithum_current_2026_fall_004",
    raw_title: "Iliad",
    raw_creator: "Homer",
    source_rank: "4",
    source_section: "Fall",
    source_url: "https://www.college.columbia.edu/core-curriculum/classes/literature-humanities",
    source_citation: "Columbia Literature Humanities current readings; Fall list",
    matched_work_id: "work_canon_iliad",
    match_method: "title_creator_exact",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.80",
    supports: "required_current_reading",
    match_status: "matched_current_path",
    notes: "Named required current reading."
  ),
  item(
    source_id: "columbia_lithum_current_2026",
    source_item_id: "columbia_lithum_current_2026_fall_003",
    raw_title: "Genesis",
    raw_creator: "Hebrew Bible / Tanakh narrative tradition",
    source_rank: "3",
    source_section: "Fall",
    source_url: "https://www.college.columbia.edu/core-curriculum/classes/literature-humanities",
    source_citation: "Columbia Literature Humanities current readings; Fall list",
    matched_work_id: "work_candidate_me_lit_genesis",
    match_method: "title_match_scripture_book",
    match_confidence: "0.90",
    evidence_type: "representative_selection",
    evidence_weight: "0.60",
    supports: "required_reader_item",
    match_status: "represented_by_selection",
    notes: "Asterisked Lit Hum Reader item; verify full-book versus excerpt."
  ),
  item(
    source_id: "columbia_lithum_historical_1937_present",
    source_item_id: "columbia_lithum_hist_aeschylus_oresteia",
    raw_title: "Aeschylus ORESTEIA",
    raw_creator: "Aeschylus",
    raw_date: "1937-present",
    source_rank: "1",
    source_section: "Author Text / Academic Years",
    source_url: "https://www.college.columbia.edu/core-curriculum/lit-hum-texts-1937-2020",
    source_citation: "Columbia Lit Hum texts 1937-present",
    matched_work_id: "work_canon_oresteia",
    match_method: "title_creator_exact",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.75",
    supports: "historical_required_reading",
    match_status: "matched_current_path",
    notes: "Long-run required historical listing."
  ),
  item(
    source_id: "princeton_humanities_sequences_2024",
    source_item_id: "princeton_humseq_2024_western_002",
    raw_title: "The Odyssey",
    raw_creator: "Homer",
    source_rank: "2",
    source_section: "HUM 216-219 Interdisciplinary Approaches to Western Culture",
    source_url: "https://humstudies.princeton.edu/wp-content/uploads/sites/3/2024/07/HumanitiesSequence2024.pdf",
    source_citation: "Princeton Humanities Sequence 2024 selected readings",
    matched_work_id: "work_canon_odyssey",
    match_method: "title_creator_exact",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.65",
    supports: "selected_reading",
    match_status: "matched_current_path",
    notes: "Selected reading, not full syllabus."
  ),
  item(
    source_id: "princeton_humanities_sequences_2024",
    source_item_id: "princeton_humseq_2024_east_asian_005",
    raw_title: "Princess Mononoke",
    raw_creator: "Hayao Miyazaki",
    source_section: "HUM 233-234 East Asian Humanities",
    source_url: "https://humstudies.princeton.edu/wp-content/uploads/sites/3/2024/07/HumanitiesSequence2024.pdf",
    source_citation: "Princeton Humanities Sequence 2024 selected readings",
    match_method: "media_boundary",
    evidence_type: "boundary_context",
    evidence_weight: "0.10",
    supports: "selected_media_item",
    match_status: "out_of_scope",
    notes: "Film/media boundary; do not import as literature item."
  ),
  item(
    source_id: "princeton_humanities_sequences_2024",
    source_item_id: "princeton_humseq_2024_near_eastern_005",
    raw_title: "The Qur'an: A New Translation",
    raw_creator: "M.A.S. Abdel Haleem",
    source_section: "HUM 247-248 Near Eastern Humanities",
    source_url: "https://humstudies.princeton.edu/wp-content/uploads/sites/3/2024/07/HumanitiesSequence2024.pdf",
    source_citation: "Princeton Humanities Sequence 2024 selected readings",
    matched_work_id: "work_canon_quran",
    match_method: "translation_to_scripture_match",
    match_confidence: "0.85",
    evidence_type: "representative_selection",
    evidence_weight: "0.45",
    supports: "selected_scripture_boundary",
    match_status: "matched_current_path",
    notes: "Translation/edition row; scripture boundary."
  ),
  item(
    source_id: "oxford_worlds_classics_online",
    source_item_id: "oxford_owc_202512_0003",
    raw_title: "Beowulf: The Fight at Finnsburh",
    raw_creator: "Kevin Crossley-Holland; Heather O'Donoghue",
    source_rank: "3",
    source_section: "OUP_OWC_Titles_List_202512.xlsx",
    source_url: "https://www.oupjapan.co.jp/sites/default/files/contents/academic/owc/media/OUP_OWC_Titles_List_202512.xlsx",
    source_citation: "OUP Japan OWC Complete List, updated 2025-12-09",
    matched_work_id: "work_canon_beowulf",
    match_method: "series_title_match",
    match_confidence: "0.95",
    evidence_type: "inclusion",
    evidence_weight: "0.25",
    supports: "publisher_series_presence",
    match_status: "matched_current_path",
    notes: "Edition-series evidence only; contributors are translator/editor metadata."
  ),
  item(
    source_id: "princeton_damrosch_world_literature_2003",
    source_item_id: "princeton_damrosch_2003_ch01_gilgameshs_quest",
    raw_title: "Gilgamesh's Quest",
    raw_creator: "David Damrosch",
    raw_date: "2003",
    source_rank: "1",
    source_section: "Part One. Circulation",
    source_url: "https://books.google.com/books/about/What_is_World_Literature.html?id=yY-17mtp9R8C",
    source_citation: "Damrosch, What Is World Literature?, ch. 1",
    matched_work_id: "work_canon_epic_of_gilgamesh",
    match_method: "context_anchor",
    match_confidence: "0.80",
    evidence_type: "boundary_context",
    evidence_weight: "0.10",
    supports: "context_method_case_study",
    match_status: "matched_current_path",
    notes: "Context/circulation case study only; not reading-list inclusion evidence."
  ),
  item(
    source_id: "e012_norton_african_american_lit_4e_v1_2025",
    source_item_id: "e012_naal4_v1_equiano_interesting_narrative",
    raw_title: "The Interesting Narrative of the Life of Olaudah Equiano, or Gustavus Vassa, the African, Written by Himself",
    raw_creator: "Olaudah Equiano",
    raw_date: "1789",
    source_rank: "1",
    source_section: "The Literature of Slavery and Freedom 1746-1865",
    source_url: "https://seagull.wwnorton.com/africanamericanlit4/TOC/V1",
    source_citation: "W. W. Norton public TOC PDF",
    matched_work_id: "work_candidate_mandatory_equiano_interesting_narrative",
    match_method: "title_creator_match",
    match_confidence: "0.95",
    evidence_type: "representative_selection",
    evidence_weight: "0.65",
    supports: "field_anthology_selection",
    match_status: "represented_by_selection",
    notes: "TOC lists Volume I chapter selections; do not treat as complete-work proof."
  ),
  item(
    source_id: "e012_norton_african_american_lit_4e_v1_2025",
    source_item_id: "e012_naal4_v1_dubois_souls",
    raw_title: "The Souls of Black Folk",
    raw_creator: "W. E. B. Du Bois",
    raw_date: "1903",
    source_rank: "2",
    source_section: "Literature of the Reconstruction to the New Negro Renaissance",
    source_url: "https://seagull.wwnorton.com/africanamericanlit4/TOC/V1",
    source_citation: "W. W. Norton public TOC PDF",
    matched_work_id: "work_canon_souls_of_black_folk",
    match_method: "title_creator_current_path",
    match_confidence: "0.98",
    evidence_type: "representative_selection",
    evidence_weight: "0.65",
    supports: "field_anthology_selection",
    match_status: "represented_by_selection",
    notes: "Current path exists; TOC lists selected internal sections."
  ),
  item(
    source_id: "e012_norton_african_american_lit_4e_v1_2025",
    source_item_id: "e012_naal4_v1_larsen_passing",
    raw_title: "Passing",
    raw_creator: "Nella Larsen",
    raw_date: "1929",
    source_rank: "3",
    source_section: "Harlem Renaissance, 1919-1940",
    source_url: "https://seagull.wwnorton.com/africanamericanlit4/TOC/V1",
    source_citation: "W. W. Norton public TOC PDF",
    matched_work_id: "work_candidate_completion_lit_passing",
    match_method: "title_creator_match",
    match_confidence: "1.00",
    evidence_type: "inclusion",
    evidence_weight: "0.65",
    supports: "field_anthology_selection",
    match_status: "matched_current_path",
    notes: "High title-collision risk; creator required."
  ),
  item(
    source_id: "e012_norton_african_american_lit_4e_v2_2025",
    source_item_id: "e012_naal4_v2_ellison_invisible_man",
    raw_title: "Invisible Man",
    raw_creator: "Ralph Ellison",
    raw_date: "1952",
    source_rank: "1",
    source_section: "Realism, Naturalism, Modernism, 1940-1960",
    source_url: "https://seagull.wwnorton.com/africanamericanlit4/TOC/V2",
    source_citation: "W. W. Norton public TOC PDF",
    matched_work_id: "work_canon_invisible_man_ellison",
    match_method: "title_creator_current_path",
    match_confidence: "0.98",
    evidence_type: "representative_selection",
    evidence_weight: "0.65",
    supports: "field_anthology_selection",
    match_status: "represented_by_selection",
    notes: "Distinguish from H. G. Wells title collision."
  ),
  item(
    source_id: "e012_norton_african_american_lit_4e_v2_2025",
    source_item_id: "e012_naal4_v2_brooks_maud_martha",
    raw_title: "Maud Martha",
    raw_creator: "Gwendolyn Brooks",
    raw_date: "1953",
    source_rank: "2",
    source_section: "Realism, Naturalism, Modernism, 1940-1960",
    source_url: "https://seagull.wwnorton.com/africanamericanlit4/TOC/V2",
    source_citation: "W. W. Norton public TOC PDF",
    match_method: "no_local_candidate",
    evidence_type: "inclusion",
    evidence_weight: "0.60",
    supports: "field_anthology_selection",
    match_status: "unmatched",
    notes: "Candidate row likely needed; verify whether anthology gives full work or excerpt."
  ),
  item(
    source_id: "e012_norton_african_american_lit_4e_v2_2025",
    source_item_id: "e012_naal4_v2_whitehead_nickel_boys",
    raw_title: "The Nickel Boys",
    raw_creator: "Colson Whitehead",
    raw_date: "2019",
    source_rank: "3",
    source_section: "The Contemporary Period",
    source_url: "https://seagull.wwnorton.com/africanamericanlit4/TOC/V2",
    source_citation: "W. W. Norton public TOC PDF",
    match_method: "no_local_candidate",
    evidence_type: "inclusion",
    evidence_weight: "0.60",
    supports: "field_anthology_selection",
    match_status: "unmatched",
    notes: "TOC sub-selection is The Match; likely represented-by-selection after candidate creation."
  )
]

source_item_rows = read_tsv(SOURCE_ITEMS_FILE)
source_items_by_id = source_item_rows.to_h { |row| [row["source_item_id"], row] }
rows.each { |row| source_items_by_id[row["source_item_id"]] = row }
write_tsv(SOURCE_ITEMS_FILE, SOURCE_ITEM_HEADERS, source_items_by_id.values)

evidence_rows = read_tsv(EVIDENCE_FILE)
evidence_by_id = evidence_rows.to_h { |row| [row["evidence_id"], row] }
rows.each do |row|
  next if row["matched_work_id"].to_s.empty?
  next if row["match_status"] == "out_of_scope"

  packet_id = case row["source_id"]
              when /^e008_/ then "X001"
              when /^library_of_america|^e012_loa/ then "X002"
              when /^icelandic|^philobiblon|^arlima|^dante_/ then "X003"
              when /^norton_english|^longman_|^broadview_/ then "X004"
              when /^columbia|^princeton|^oxford_/ then "X005"
              when /^e012_norton/ then "X006"
              else "X001-X006"
              end
  strength = if row["evidence_weight"].to_f >= 0.75
               "strong"
             elsif row["evidence_weight"].to_f >= 0.5
               "moderate"
             else
               "weak"
             end
  evidence = evidence_for(row, packet_id, strength)
  evidence_by_id[evidence["evidence_id"]] = evidence
end
write_tsv(EVIDENCE_FILE, EVIDENCE_HEADERS, evidence_by_id.values)

manifest = YAML.load_file(MANIFEST_FILE)
manifest["status"] = "source_item_pilot_x001_x006_ingested"
manifest["artifacts"]["source_registry"] = "e001_e012_registered"
manifest["artifacts"]["source_items"] = "e001_ingested_x001_x006_pilot_ingested"
manifest["artifacts"]["evidence"] = "e001_ingested_x001_x006_pilot_ingested"
manifest["source_item_extraction_batch_x001_x006"] = {
  "pilot_source_items_added_or_updated" => rows.size,
  "pilot_evidence_rows_added_or_updated" => rows.count { |row| !row["matched_work_id"].to_s.empty? && row["match_status"] != "out_of_scope" },
  "status" => "pilot_ingested_needs_full_extraction_and_matching",
  "direct_replacements" => 0
}
File.write(MANIFEST_FILE, manifest.to_yaml)

puts "ingested or updated #{rows.size} X001-X006 pilot source-item rows"
