#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "yaml"

ROOT = File.expand_path("..", __dir__)
BUILD_DIR = File.join(ROOT, "_planning", "canon_build")
TABLE_DIR = File.join(BUILD_DIR, "tables")
REGISTRY_FILE = File.join(TABLE_DIR, "canon_source_registry.tsv")
MANIFEST_FILE = File.join(BUILD_DIR, "manifests", "canon_build_manifest.yml")

HEADERS = %w[
  source_id source_title source_type source_scope source_date source_citation edition editors_or_authors
  publisher coverage_limits extraction_method packet_ids extraction_status notes
].freeze

def read_registry(path)
  return [] unless File.exist?(path)

  CSV.read(path, headers: true, col_sep: "\t").map(&:to_h)
end

def write_registry(path, rows)
  CSV.open(path, "w", col_sep: "\t", write_headers: true, headers: HEADERS) do |csv|
    rows.sort_by { |row| row["source_id"].to_s }.each do |row|
      csv << HEADERS.map { |header| row[header] }
    end
  end
end

new_rows = [
  {
    "source_id" => "columbia_lithum_current_2026",
    "source_title" => "Columbia Literature Humanities current reading list",
    "source_type" => "university_core_reading_list",
    "source_scope" => "Current Columbia Lit Hum two-semester required readings",
    "source_date" => "2026",
    "source_citation" => "https://www.college.columbia.edu/core-curriculum/classes/literature-humanities",
    "edition" => "current web page",
    "editors_or_authors" => "Columbia College Core Curriculum",
    "publisher" => "Columbia College",
    "coverage_limits" => "Western/core-curriculum weighted; includes instructor-choice slots and reader excerpts",
    "extraction_method" => "Extract listed Fall/Spring works; classify complete work versus excerpt/reader item; match by title, author, and collection",
    "packet_ids" => "E007",
    "extraction_status" => "ready_for_extraction",
    "notes" => "High-value teaching-canon layer; not global by itself"
  },
  {
    "source_id" => "columbia_lithum_historical_1937_present",
    "source_title" => "Columbia Literature Humanities texts, 1937-present",
    "source_type" => "university_core_historical_reading_list",
    "source_scope" => "Literature Humanities works and years studied since 1937",
    "source_date" => "1937-present",
    "source_citation" => "https://www.college.columbia.edu/core-curriculum/lit-hum-texts-1937-2020",
    "edition" => "living historical list",
    "editors_or_authors" => "Columbia College Core Curriculum",
    "publisher" => "Columbia College",
    "coverage_limits" => "Many texts historically read in excerpts; instructor-choice list is nonrequired",
    "extraction_method" => "Extract author/text/year ranges; mark required, historical, instructor-choice, and excerpt status",
    "packet_ids" => "E007",
    "extraction_status" => "ready_for_extraction",
    "notes" => "Useful for long-run Western teaching-canon persistence"
  },
  {
    "source_id" => "princeton_humanities_sequences_2024",
    "source_title" => "Princeton Humanities Sequences brochure",
    "source_type" => "university_sequence_selected_readings",
    "source_scope" => "Selected readings for Western, East Asian, and Near Eastern Humanities sequences",
    "source_date" => "2024",
    "source_citation" => "https://humstudies.princeton.edu/wp-content/uploads/sites/3/2024/07/HumanitiesSequence2024.pdf",
    "edition" => "2024 brochure",
    "editors_or_authors" => "Princeton Program in Humanistic Studies",
    "publisher" => "Princeton University",
    "coverage_limits" => "Selected readings only, not complete syllabi; includes visual/media items",
    "extraction_method" => "Extract selected reading anchors by sequence; mark text, anthology, film/music, or reference",
    "packet_ids" => "E007",
    "extraction_status" => "ready_for_extraction",
    "notes" => "Comparative layer including East Asian and Near Eastern tracks"
  },
  {
    "source_id" => "princeton_humanistic_studies_catalog",
    "source_title" => "Princeton Humanistic Studies course catalog/reference",
    "source_type" => "university_course_catalog",
    "source_scope" => "Humanities sequence scope and course descriptions",
    "source_date" => "2025-2026",
    "source_citation" => "https://ua.princeton.edu/fields-study/minors/humanistic-studies",
    "edition" => "current catalog",
    "editors_or_authors" => "Princeton University",
    "publisher" => "Princeton University",
    "coverage_limits" => "Course descriptions, not line-item reading lists",
    "extraction_method" => "Use for scope metadata and packet limits only",
    "packet_ids" => "E007",
    "extraction_status" => "context_only",
    "notes" => "Supports scope, not individual work evidence"
  },
  {
    "source_id" => "oxford_worlds_classics_online",
    "source_title" => "Oxford World's Classics online/title-list layer",
    "source_type" => "publisher_reference_series",
    "source_scope" => "Oxford World's Classics catalogue/reference series, broad classic literature coverage",
    "source_date" => "current",
    "source_citation" => "https://academic.oup.com/products-for-institutions/pages/purchase-oxford-worlds-classics; https://www.oupjapan.co.jp/en/academic/owc/index.shtml",
    "edition" => "current online catalogue/title list",
    "editors_or_authors" => "Oxford University Press editors",
    "publisher" => "Oxford University Press",
    "coverage_limits" => "Publisher list; skewed to available classic editions; includes nonliterary philosophy/history/religion",
    "extraction_method" => "Download or parse official title list where accessible; classify literary work, boundary item, edition, or false positive",
    "packet_ids" => "E007",
    "extraction_status" => "in_progress",
    "notes" => "Useful for edition/translation and alias checks; not a canon list"
  },
  {
    "source_id" => "princeton_damrosch_world_literature_2003",
    "source_title" => "What Is World Literature?",
    "source_type" => "world_literature_reference_method",
    "source_scope" => "Princeton University Press world-literature theory/reference layer",
    "source_date" => "2003",
    "source_citation" => "https://books.google.com/books/about/What_is_World_Literature.html?id=yY-17mtp9R8C",
    "edition" => "2003",
    "editors_or_authors" => "David Damrosch",
    "publisher" => "Princeton University Press",
    "coverage_limits" => "Not a reading list; case-study/reference value only",
    "extraction_method" => "Extract only case-study anchors and methodological warnings about circulation/translation",
    "packet_ids" => "E007",
    "extraction_status" => "context_only",
    "notes" => "Use to prevent treating world literature as a simple fixed list"
  },
  {
    "source_id" => "e008_perseus_catalog_greek_latin_works",
    "source_title" => "Perseus Catalog",
    "source_type" => "metadata_catalog",
    "source_scope" => "Greek and Latin authors/works, editions, translations, series metadata",
    "source_date" => "online catalog",
    "source_citation" => "https://catalog.perseus.org/catalog",
    "edition" => "1.0",
    "editors_or_authors" => "Perseus Digital Library",
    "publisher" => "Perseus Digital Library / Tufts",
    "coverage_limits" => "Work metadata, not canon ranking; includes fragmentary and non-literary material",
    "extraction_method" => "Extract title, author, language, series, and subject facets; match to path by title, creator, aliases, and original language",
    "packet_ids" => "E008",
    "extraction_status" => "ready_public_metadata",
    "notes" => "Best open machine-readable crosswalk layer for Greek/Latin metadata"
  },
  {
    "source_id" => "e008_loeb_classical_library_digital",
    "source_title" => "Loeb Classical Library",
    "source_type" => "digital_primary_text_series",
    "source_scope" => "Greek and Latin literature, ca. 700 BCE-700 CE",
    "source_date" => "current online database",
    "source_citation" => "Harvard University Press / Loeb Classical Library; Rutgers database description",
    "edition" => "digital",
    "editors_or_authors" => "Loeb editors",
    "publisher" => "Harvard University Press",
    "coverage_limits" => "Subscription text; public metadata uneven; Loeb presence is not automatic canon status",
    "extraction_method" => "Use public catalog/Perseus Loeb-series metadata; do not scrape texts; classify complete works, fragments, and selections",
    "packet_ids" => "E008",
    "extraction_status" => "ready_with_access_limits",
    "notes" => "High-value source layer for canonical Greek/Latin coverage"
  },
  {
    "source_id" => "e008_oxford_classical_dictionary_online",
    "source_title" => "Oxford Classical Dictionary",
    "source_type" => "reference_encyclopedia",
    "source_scope" => "Classical world reference entries, including literature, history, philosophy, religion, and reception",
    "source_date" => "2015-, updated online",
    "source_citation" => "https://academic.oup.com/edited-volume/61673?pageSize=20&sort=titlesort&subSite=classics&t=ORE_CLA%3AREFCLA004",
    "edition" => "online living edition",
    "editors_or_authors" => "Lucy Grig and contributors",
    "publisher" => "Oxford University Press",
    "coverage_limits" => "Many entries gated; validates author/work importance and boundaries, not path inclusion alone",
    "extraction_method" => "Search author/work entries and subject facets; record entry presence, subject, access status, and boundary notes",
    "packet_ids" => "E008",
    "extraction_status" => "ready_partial_public",
    "notes" => "Useful for boundary adjudication and author/work authority"
  },
  {
    "source_id" => "e008_oxford_scholarly_editions_oct",
    "source_title" => "Oxford Classical Texts via Oxford Scholarly Editions Online",
    "source_type" => "critical_edition_series",
    "source_scope" => "Greek and Latin critical editions/translations including Oxford Classical Texts",
    "source_date" => "current online product",
    "source_citation" => "OUP Classical Studies / Oxford Scholarly Editions Online",
    "edition" => "online",
    "editors_or_authors" => "OUP editors",
    "publisher" => "Oxford University Press",
    "coverage_limits" => "Subscription; direct title list may be incomplete publicly",
    "extraction_method" => "Use OUP public series/product metadata plus Perseus series facet for OCT records; classify as critical-edition evidence",
    "packet_ids" => "E008",
    "extraction_status" => "partial_public_metadata",
    "notes" => "Strong edition-history layer, weaker for popular canon"
  },
  {
    "source_id" => "e008_cambridge_greek_latin_classics",
    "source_title" => "Cambridge Greek and Latin Classics",
    "source_type" => "commentary_text_series",
    "source_scope" => "Commented Greek/Latin texts for advanced students and scholars",
    "source_date" => "current Cambridge Core series",
    "source_citation" => "https://www.cambridge.org/core/series/cambridge-greek-and-latin-classics/9900A4E001E0221C90A6CAD4E6F45A1B",
    "edition" => "series",
    "editors_or_authors" => "Series editors",
    "publisher" => "Cambridge University Press",
    "coverage_limits" => "Selective pedagogical/commentary series, not comprehensive",
    "extraction_method" => "Extract series titles, authors, publication dates, descriptions; match by work/book/selection",
    "packet_ids" => "E008",
    "extraction_status" => "ready_public_metadata",
    "notes" => "Useful for syllabus-level centrality and book-level selection evidence"
  },
  {
    "source_id" => "e008_phi_classical_latin_texts",
    "source_title" => "Packard Humanities Institute Classical Latin Texts",
    "source_type" => "latin_text_corpus",
    "source_scope" => "Latin literary texts before AD 200 plus selected later antiquity",
    "source_date" => "online from PHI CD-ROM 5.3",
    "source_citation" => "https://latin.packhum.org/about",
    "edition" => "online",
    "editors_or_authors" => "Packard Humanities Institute",
    "publisher" => "Packard Humanities Institute",
    "coverage_limits" => "Latin only; mostly pre-200 CE; text license permits personal study, not bulk copying",
    "extraction_method" => "Extract author/work metadata only: author number, work title, work number, reference edition, URL",
    "packet_ids" => "E008",
    "extraction_status" => "ready_public_metadata",
    "notes" => "Best open Latin corpus layer for detecting absent Latin authors/works"
  },
  {
    "source_id" => "longman_brit_lit_middle_ages_1a_4e",
    "source_title" => "The Longman Anthology of British Literature: The Middle Ages, Vol. 1A",
    "source_type" => "period_anthology",
    "source_scope" => "British Isles medieval literature; Old English, Irish/Welsh, Anglo-Norman, and Middle English",
    "source_date" => "2010",
    "source_citation" => "Pearson product/TOC: https://www.pearson.com/en-us/subject-catalog/p/longman-anthology-of-british-literature-the-the-middle-ages-volume-1a/P200000002130/9780205655304",
    "edition" => "4th ed.",
    "editors_or_authors" => "David Damrosch; Kevin Dettmar; Christopher Baswell; Anne Howland Schotter",
    "publisher" => "Pearson",
    "coverage_limits" => "British-focused; many excerpt and context items",
    "extraction_method" => "Extract public TOC titles only; mark complete, excerpt, selection, and context rows",
    "packet_ids" => "E009",
    "extraction_status" => "public_toc_ready",
    "notes" => "Strong Old English and Middle English anchor layer"
  },
  {
    "source_id" => "broadview_brit_lit_medieval_r3_2023",
    "source_title" => "The Broadview Anthology of British Literature, Vol. 1: The Medieval Period",
    "source_type" => "period_anthology",
    "source_scope" => "British medieval literature; Old English, Anglo-Norman, Middle English, religious, and context material",
    "source_date" => "2023",
    "source_citation" => "Broadview official page: https://broadviewpress.com/product/the-broadview-anthology-of-british-literature-volume-1-the-medieval-period-revised-third-edition/",
    "edition" => "Revised 3rd ed.",
    "editors_or_authors" => "Joseph Black and coeditors",
    "publisher" => "Broadview Press",
    "coverage_limits" => "Public TOC available; companion-site items need boundary tags",
    "extraction_method" => "Extract publisher TOC anchors; match whole works versus selections",
    "packet_ids" => "E009",
    "extraction_status" => "public_toc_ready",
    "notes" => "Best public layer for Old English elegies, Beowulf, Pearl, Gawain, Julian, Kempe, and drama"
  },
  {
    "source_id" => "broadview_medieval_drama_2012",
    "source_title" => "The Broadview Anthology of Medieval Drama",
    "source_type" => "drama_anthology",
    "source_scope" => "Medieval drama across Latin, continental, and English traditions",
    "source_date" => "2012",
    "source_citation" => "Broadview official page: https://broadviewpress.com/product/the-broadview-anthology-of-medieval-drama/",
    "edition" => "1st ed.",
    "editors_or_authors" => "Christina M. Fitzgerald; John T. Sebastian",
    "publisher" => "Broadview Press",
    "coverage_limits" => "Drama-only; includes documents and context sources",
    "extraction_method" => "Extract play titles and context documents separately",
    "packet_ids" => "E009",
    "extraction_status" => "public_toc_ready",
    "notes" => "Useful for Hrotsvitha, Quem Quaeritis, York cycle, Everyman, and early drama checks"
  },
  {
    "source_id" => "arlima_medieval_literature",
    "source_title" => "ARLIMA: Archives de litterature du Moyen Age",
    "source_type" => "bibliographic_database",
    "source_scope" => "European medieval authors, works, themes, and manuscripts",
    "source_date" => "ongoing",
    "source_citation" => "ARLIMA: https://www.arlima.net/",
    "edition" => "online",
    "editors_or_authors" => "ARLIMA editors",
    "publisher" => "ARLIMA",
    "coverage_limits" => "Bibliographic support, not anthology selection evidence",
    "extraction_method" => "Use author/work pages for aliases, manuscript witnesses, and bibliographic authority",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "High-value authority layer for Old French, Arthurian, Anglo-Norman, and Latin-adjacent records"
  },
  {
    "source_id" => "lancelot_grail_lacy_5vol",
    "source_title" => "Lancelot-Grail: The Old French Vulgate and Post-Vulgate Cycles in Translation",
    "source_type" => "arthurian_cycle_translation",
    "source_scope" => "Old French Arthurian Vulgate and Post-Vulgate cycle",
    "source_date" => "2010/2013",
    "source_citation" => "Routledge page: https://www.routledge.com/Lancelot-Grail-5-Volumes-Routledge-Revivals-The-Old-French-Vulgate--Post-Vulgate-Cycles-in-Translation/Lacy/p/book/9780415877275",
    "edition" => "5 vols.",
    "editors_or_authors" => "Norris J. Lacy",
    "publisher" => "Routledge",
    "coverage_limits" => "Copyrighted translation; public metadata and TOC only",
    "extraction_method" => "Extract cycle and section structure, not translation text",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Anchor for Grail, Lancelot, Quest, and Death of Arthur relation mapping"
  },
  {
    "source_id" => "bibliotheca_augustana_germanica",
    "source_title" => "Bibliotheca Augustana: Bibliotheca Germanica",
    "source_type" => "digital_text_collection",
    "source_scope" => "German literature chronology including Old High German, Middle High German, and Early New High German",
    "source_date" => "various",
    "source_citation" => "Chronology page: https://www.hs-augsburg.de/~harsch/germanica/Chronologie/d_chrono.html",
    "edition" => "online",
    "editors_or_authors" => "Ulrich Harsch",
    "publisher" => "HS Augsburg",
    "coverage_limits" => "Edition provenance uneven; not canon-selection evidence",
    "extraction_method" => "Use as public text/access and alias layer; verify against specialist metadata",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Middle High German anchor for Nibelungenlied, courtly romance, and Minnesang"
  },
  {
    "source_id" => "wimmer_medieval_german_anthology",
    "source_title" => "Anthology of Medieval German Literature",
    "source_type" => "teaching_anthology",
    "source_scope" => "Middle High German anthology with parallel and translation apparatus",
    "source_date" => "1991",
    "source_citation" => "Google Books metadata: https://books.google.com/books/about/Anthology_of_medieval_German_literature.html?id=--QfAQAAIAAJ",
    "edition" => "2nd illustrated ed.",
    "editors_or_authors" => "Albert K. Wimmer; W. T. H. Jackson",
    "publisher" => "Vande Vere",
    "coverage_limits" => "Public metadata only; line-item TOC not fully extractable",
    "extraction_method" => "Registry only unless physical or verified TOC access is available",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_only",
    "notes" => "Middle High German anthology layer; useful but blocked for exhaustive items"
  },
  {
    "source_id" => "minnereden_lovesongs_digital",
    "source_title" => "Minnereden and Love Songs - digital",
    "source_type" => "specialist_digital_corpus",
    "source_scope" => "Late medieval German Minnereden and love songs, c. 1280-1530",
    "source_date" => "2025-2027",
    "source_citation" => "Heidelberg project page: https://www.uni-heidelberg.de/en/minnereden-and-love-songs-digital",
    "edition" => "online",
    "editors_or_authors" => "Ludger Lieb and project collaborators",
    "publisher" => "Heidelberg/Bonn",
    "coverage_limits" => "Focused on late lyric/love discourse, not epic romance",
    "extraction_method" => "Use for metadata on lyric and Minnerede corpora",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Checks Walther and late Middle High German lyric over- and under-representation"
  },
  {
    "source_id" => "icelandic_saga_database",
    "source_title" => "Icelandic Saga Database",
    "source_type" => "digital_text_collection",
    "source_scope" => "Sagas of Icelanders, Icelandic plus public-domain translations",
    "source_date" => "ongoing",
    "source_citation" => "Project/index: https://sagadb.org/ ; A-Z: https://sagadb.org/index_az",
    "edition" => "online",
    "editors_or_authors" => "Sveinbjorn Thordarson",
    "publisher" => "Icelandic Saga Database",
    "coverage_limits" => "Family sagas only; excludes Eddas, kings' sagas, and legendary sagas",
    "extraction_method" => "Extract saga titles, language availability, and translation status",
    "packet_ids" => "E009",
    "extraction_status" => "public_index_ready",
    "notes" => "Anchor for Njals, Egils, Gisli, Laxdaela, Grettir; avoid importing all sagas as gaps"
  },
  {
    "source_id" => "dumbarton_oaks_medieval_library",
    "source_title" => "Dumbarton Oaks Medieval Library",
    "source_type" => "edited_text_series",
    "source_scope" => "Medieval Latin, Byzantine Greek, Old English, and medieval Iberian bilingual editions",
    "source_date" => "2010-ongoing",
    "source_citation" => "Series: https://domedieval.org/ ; 2024 catalog: https://domedieval.org/wp-content/uploads/2024/09/DOML-2024-catalog.pdf",
    "edition" => "series",
    "editors_or_authors" => "Dumbarton Oaks Medieval Library language editors",
    "publisher" => "Harvard University Press",
    "coverage_limits" => "Series catalog; not a canon list; copyrighted translations",
    "extraction_method" => "Extract volume metadata, language, work identity, and edition scope",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Strong Latin, Old English, and Iberian authority layer"
  },
  {
    "source_id" => "philobiblon_iberian_romance",
    "source_title" => "PhiloBiblon",
    "source_type" => "ibero_romance_bibliographic_database",
    "source_scope" => "Medieval and early Renaissance Iberian Romance texts and witnesses",
    "source_date" => "legacy frozen 2025",
    "source_citation" => "PhiloBiblon: https://philobiblon.upf.edu/html/",
    "edition" => "online",
    "editors_or_authors" => "BETA/BITAGAP/BITECA teams",
    "publisher" => "UC Berkeley/UPF",
    "coverage_limits" => "Bibliographic database, not anthology; legacy/viewer split",
    "extraction_method" => "Use BETA, BITAGAP, and BITECA records for title, witness, language, and authority",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Primary Iberian crosswalk layer"
  },
  {
    "source_id" => "osta_2_old_spanish_textual_archive",
    "source_title" => "Old Spanish Textual Archive 2.0",
    "source_type" => "linguistic_corpus",
    "source_scope" => "Old Spanish corpus from semi-paleographic medieval transcriptions",
    "source_date" => "2026 resource notice",
    "source_citation" => "Instituto Cervantes notice: https://hispanismo.cervantes.es/recursos/old-spanish-textual-archive-osta-version-20",
    "edition" => "v2.0",
    "editors_or_authors" => "Hispanic Seminary of Medieval Studies collaborators",
    "publisher" => "Hispanic Seminary of Medieval Studies",
    "coverage_limits" => "Linguistic corpus; not literary canon evidence",
    "extraction_method" => "Use only for access/provenance and text availability after metadata verification",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Useful for Cid, Libro de buen amor, and Conde Lucanor records"
  },
  {
    "source_id" => "dante_digital_anchor_layer",
    "source_title" => "Princeton Dante Project and Digital Dante",
    "source_type" => "specialist_digital_project",
    "source_scope" => "Dante texts, Commedia, minor works, commentary, translation, and reference metadata",
    "source_date" => "1999-ongoing",
    "source_citation" => "PDP: https://dante.princeton.edu/ ; MDR PDP: https://mdr-maa.org/resource/princeton-dante-project/ ; Digital Dante MDR: https://mdr-maa.org/resource/digital-dante/",
    "edition" => "online",
    "editors_or_authors" => "Robert Hollander; Teodolinda Barolini and collaborators",
    "publisher" => "Princeton/Columbia",
    "coverage_limits" => "Dante-specific; not broader Trecento evidence",
    "extraction_method" => "Use for Dante work identity, minor-work coverage, commentary, and text access",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Supports Divine Comedy and Vita Nuova; does not settle Petrarch/Boccaccio coverage"
  },
  {
    "source_id" => "mgh_medieval_latin_sources",
    "source_title" => "Monumenta Germaniae Historica / dMGH",
    "source_type" => "critical_source_series",
    "source_scope" => "Medieval Latin historical, legal, and ecclesiastical sources c. 500-1500",
    "source_date" => "1826-ongoing",
    "source_citation" => "MGH project: https://mgh.bbaw.de/en/en-1 ; overview: https://www.kb.nl/en/bron/monumenta-germaniae-historica-digital",
    "edition" => "series",
    "editors_or_authors" => "MGH editors",
    "publisher" => "MGH / historical academies",
    "coverage_limits" => "Mostly history/documentary Latin; literary boundary risk",
    "extraction_method" => "Use as source/provenance layer, not automatic literature inclusion",
    "packet_ids" => "E009",
    "extraction_status" => "metadata_ready",
    "notes" => "Medieval Latin context layer for chronicles, hagiography, letters, and institutional texts"
  },
  {
    "source_id" => "norton_english_lit_11e_full_2024",
    "source_title" => "The Norton Anthology of English Literature",
    "source_type" => "english_literature_anthology",
    "source_scope" => "Middle Ages to twenty-first century; volumes A-F",
    "source_date" => "2024",
    "source_citation" => "W. W. Norton official 11e pages and TOC PDFs",
    "edition" => "11th ed.",
    "editors_or_authors" => "Stephen Greenblatt and coeditors",
    "publisher" => "W. W. Norton",
    "coverage_limits" => "Public TOC PDFs expose strong line-item metadata; anthology selections often excerpts",
    "extraction_method" => "Parse official volume TOC PDFs A-F; classify complete work, excerpt, poem selection, and contextual cluster",
    "packet_ids" => "E010",
    "extraction_status" => "ready_public_toc",
    "notes" => "Primary English/British teaching-canon layer"
  },
  {
    "source_id" => "longman_british_lit_period_volumes_2009_2017",
    "source_title" => "The Longman Anthology of British Literature",
    "source_type" => "english_literature_anthology",
    "source_scope" => "British Isles, medieval through contemporary; period volumes",
    "source_date" => "2009-2017",
    "source_citation" => "Pearson public product/TOC pages",
    "edition" => "4th/5th ed. period volumes",
    "editors_or_authors" => "David Damrosch; Kevin Dettmar and coeditors",
    "publisher" => "Pearson/Longman",
    "coverage_limits" => "Edition mix across period volumes; strong public TOCs but not one uniform edition",
    "extraction_method" => "Extract Pearson TOC rows by volume; preserve edition/date per volume; match as evidence only",
    "packet_ids" => "E010",
    "extraction_status" => "ready_public_toc",
    "notes" => "Useful for British Isles breadth, women writers, and regional/context clusters"
  },
  {
    "source_id" => "broadview_british_lit_concise_a_b_2019_2024",
    "source_title" => "Broadview Anthology of British Literature, Concise Vols. A-B",
    "source_type" => "english_literature_anthology",
    "source_scope" => "Medieval through twenty-first century",
    "source_date" => "2019-2024",
    "source_citation" => "Broadview official product pages and contents",
    "edition" => "Concise A 4th; Concise B 3rd",
    "editors_or_authors" => "Joseph Black and coeditors",
    "publisher" => "Broadview Press",
    "coverage_limits" => "Includes companion-website material; some rows are contextual, not primary works",
    "extraction_method" => "Extract official contents; mark bound-book versus website item; compare with Norton/Longman",
    "packet_ids" => "E010",
    "extraction_status" => "ready_public_toc",
    "notes" => "Modern diversity/context comparator"
  },
  {
    "source_id" => "norton_american_lit_10e_pre1865",
    "source_title" => "The Norton Anthology of American Literature, Tenth Edition, Package 1: Volumes A and B",
    "source_type" => "american_literature_anthology",
    "source_scope" => "Beginnings to 1865",
    "source_date" => "2022",
    "source_citation" => "W. W. Norton official catalogue/product metadata; public library TOCs for Vol. A",
    "edition" => "10th ed.",
    "editors_or_authors" => "Robert S. Levine; Sandra M. Gustafson",
    "publisher" => "W. W. Norton",
    "coverage_limits" => "Public TOCs uneven; many source items are selections, clusters, or excerpts",
    "extraction_method" => "Extract public TOC metadata and authorized/physical-copy title-page/TOC only; match by title, creator, alias, contained-work, and section",
    "packet_ids" => "E011",
    "extraction_status" => "in_progress",
    "notes" => "Primary teaching-anthology source for early US/colonial/antebellum literature"
  },
  {
    "source_id" => "norton_american_lit_10e_post1865",
    "source_title" => "The Norton Anthology of American Literature, Tenth Edition, Package 2: Volumes C, D, and E",
    "source_type" => "american_literature_anthology",
    "source_scope" => "1865 to present",
    "source_date" => "2022",
    "source_citation" => "W. W. Norton official catalogue/product metadata; public library TOCs for Vols. C/E; JHU metadata for Vol. D",
    "edition" => "10th ed.",
    "editors_or_authors" => "Robert S. Levine; Michael A. Elliott; Lisa Siraganian; Amy Hungerford; GerShun Avilez",
    "publisher" => "W. W. Norton",
    "coverage_limits" => "Public TOCs uneven; contemporary inclusions should be evidence, not automatic canon locks",
    "extraction_method" => "Extract visible TOC rows; encode complete_work/excerpt/selection/context; match to current path and candidate universe",
    "packet_ids" => "E011",
    "extraction_status" => "in_progress",
    "notes" => "Strong evidence layer for canonical and classroom-current US literature"
  },
  {
    "source_id" => "heath_american_lit_7e_2014",
    "source_title" => "The Heath Anthology of American Literature, Seventh Edition",
    "source_type" => "american_literature_anthology",
    "source_scope" => "Five-volume US literature anthology, beginnings to contemporary period",
    "source_date" => "2014",
    "source_citation" => "UTA/Cengage/eCampus public metadata for 7th ed. volumes",
    "edition" => "7th ed.",
    "editors_or_authors" => "Paul Lauter and coeditors",
    "publisher" => "Wadsworth/Cengage",
    "coverage_limits" => "Public metadata available by volume; full TOC access varies",
    "extraction_method" => "Extract volume TOCs where public/authorized; emphasize inclusive-canon and underrepresented-author evidence",
    "packet_ids" => "E011",
    "extraction_status" => "in_progress",
    "notes" => "Counterweight to Norton with broader/inclusive canon coverage"
  },
  {
    "source_id" => "library_of_america_catalog",
    "source_title" => "Library of America catalog and writer pages",
    "source_type" => "authoritative_edition_series",
    "source_scope" => "American literary authors, collected works, thematic anthologies, canonical editions",
    "source_date" => "current_catalog",
    "source_citation" => "https://www.loa.org/",
    "edition" => "ongoing",
    "editors_or_authors" => "Library of America editors",
    "publisher" => "Library of America",
    "coverage_limits" => "Not an anthology ranking; catalog presence is edition/reception evidence, not sole inclusion proof",
    "extraction_method" => "Extract one row per LOA volume and contained major work; match collected editions to path-level works",
    "packet_ids" => "E011",
    "extraction_status" => "in_progress",
    "notes" => "Use for edition/reception support and author/work authority"
  },
  {
    "source_id" => "e012_norton_african_american_lit_4e_v1_2025",
    "source_title" => "The Norton Anthology of African American Literature, Volume 1",
    "source_type" => "field_anthology",
    "source_scope" => "Beginnings through Harlem Renaissance",
    "source_date" => "2025",
    "source_citation" => "Henry Louis Gates Jr. et al., The Norton Anthology of African American Literature, 4th ed., W. W. Norton, 2025",
    "edition" => "4th ed.",
    "editors_or_authors" => "Henry Louis Gates Jr.; Valerie Smith; William L. Andrews; Frances Smith Foster; others",
    "publisher" => "W. W. Norton",
    "coverage_limits" => "Public TOC is available; copyrighted anthology text not extractable",
    "extraction_method" => "Extract public TOC selection rows; classify complete work, excerpt, poem, song, oral item, or sermon",
    "packet_ids" => "E012",
    "extraction_status" => "not_started",
    "notes" => "Primary African American literature teaching-canon layer"
  },
  {
    "source_id" => "e012_norton_african_american_lit_4e_v2_2025",
    "source_title" => "The Norton Anthology of African American Literature, Volume 2",
    "source_type" => "field_anthology",
    "source_scope" => "Realism, Naturalism, Modernism to the Present",
    "source_date" => "2025",
    "source_citation" => "Henry Louis Gates Jr. et al., The Norton Anthology of African American Literature, 4th ed., W. W. Norton, 2025",
    "edition" => "4th ed.",
    "editors_or_authors" => "Henry Louis Gates Jr.; Valerie Smith; Jesse McCarthy; Farah Jasmine Griffin; others",
    "publisher" => "W. W. Norton",
    "coverage_limits" => "Public TOC is available; many entries are excerpts/selections",
    "extraction_method" => "Extract public TOC; separate author representation from work representation",
    "packet_ids" => "E012",
    "extraction_status" => "not_started",
    "notes" => "Strong contemporary and Black Arts coverage"
  },
  {
    "source_id" => "e012_loa_slave_narratives",
    "source_title" => "Slave Narratives",
    "source_type" => "authoritative_collection",
    "source_scope" => "Slave narrative tradition, 1772-1864",
    "source_date" => "LOA edition",
    "source_citation" => "Library of America No. 114, edited by William L. Andrews and Henry Louis Gates Jr.",
    "edition" => "LOA series edition",
    "editors_or_authors" => "William L. Andrews; Henry Louis Gates Jr.",
    "publisher" => "Library of America",
    "coverage_limits" => "Contains ten works; not all are equal path candidates",
    "extraction_method" => "Extract work-level rows; match complete narratives and flag represented-by-collection",
    "packet_ids" => "E012",
    "extraction_status" => "not_started",
    "notes" => "Strong early/autobiographical African American layer"
  },
  {
    "source_id" => "e012_loa_african_american_poetry_2020",
    "source_title" => "African American Poetry: 250 Years of Struggle & Song",
    "source_type" => "poetry_anthology",
    "source_scope" => "African American poetry, 1770-2020",
    "source_date" => "2020",
    "source_citation" => "Library of America No. 333, edited by Kevin Young",
    "edition" => "LOA anthology",
    "editors_or_authors" => "Kevin Young",
    "publisher" => "Library of America",
    "coverage_limits" => "Poem-level evidence; not full-book evidence for every poet",
    "extraction_method" => "Extract poet and poem rows; support poet/selection basis and poetry coverage",
    "packet_ids" => "E012",
    "extraction_status" => "not_started",
    "notes" => "Modern poetry breadth layer"
  },
  {
    "source_id" => "e012_locke_new_negro_1925",
    "source_title" => "The New Negro: An Interpretation",
    "source_type" => "primary_anthology",
    "source_scope" => "Harlem Renaissance fiction, poetry, essays, art, music, and criticism",
    "source_date" => "1925",
    "source_citation" => "Alain Locke, ed., A. and C. Boni, 1925",
    "edition" => "original edition",
    "editors_or_authors" => "Alain Locke",
    "publisher" => "A. and C. Boni",
    "coverage_limits" => "Public domain TOC/full text available; anthology source distinct from contained works",
    "extraction_method" => "Extract one row per named contribution; distinguish anthology as source from contained works",
    "packet_ids" => "E012",
    "extraction_status" => "not_started",
    "notes" => "Primary Harlem Renaissance source"
  }
]

existing = read_registry(REGISTRY_FILE)
by_id = existing.to_h { |row| [row["source_id"], row] }
new_rows.each { |row| by_id[row["source_id"]] = row }
write_registry(REGISTRY_FILE, by_id.values)

manifest = YAML.load_file(MANIFEST_FILE)
manifest["status"] = "source_crosswalk_batch_e007_e012_registered"
manifest["artifacts"]["source_registry"] = "e001_e012_registered_source_items_pending"
manifest["source_crosswalk_batch_e007_e012"] = {
  "source_registry_rows_added_or_updated" => new_rows.size,
  "e007_status" => "registered_needs_extraction",
  "e008_status" => "registered_needs_classics_metadata_extraction",
  "e009_status" => "registered_needs_medieval_metadata_and_toc_extraction",
  "e010_status" => "registered_needs_english_toc_extraction",
  "e011_status" => "registered_needs_american_toc_extraction",
  "e012_status" => "registered_needs_african_american_toc_extraction"
}
File.write(MANIFEST_FILE, manifest.to_yaml)

puts "registered or updated #{new_rows.size} E007-E012 source layers"
